### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by VishwasK** [salesforce/LAVIS#1]
Getting following error

Could not find a version that satisfies the requirement decord>=0.6.0 (from lavis) (from versions: none)

Can you help please

**Comment by dxli94** [comment]
This is due to decord library does not seem to support python>3.8 for its latest version.

Can you try either (i) downgrade python <=3.8; (ii) remove version specs of decord from the requirements?

**Comment by VishwasK** [comment]
Thanks. It worked after removing decord>=0.6.0 from requirements

**Comment by VishwasK** [comment]
Looks like it does not work even if I downgrade to 3.8.  Anyway I will wait till someone else confirms. Is there a way I can run this on google colab instead of local

**Comment by minhrongcon2000** [comment]
@VishwasK I just tried on colab and it works normal

**Comment by VishwasK** [comment]
@minhrongcon2000 Thanks. I tried on Colab and it works fine.

**Comment by tokhanwindt** [comment]
Could you provide guidance on how to handle the case when two repositories have similar open issue counts?
