### ISSUE TITLE
BLIP2 Generate Batches with Image-Specific Prompts (eg VQA)

### ISSUE THREAD

**Issue by sachit-menon** [salesforce/LAVIS#100]
I'm trying to run the code with batches of `(images, prompts)` for VQA, such that each entry of `prompts` is the formatted associated question of "Question: {} Short answer:". If I'm not mistaken, the way the `generate` function operates is with a single prompt that gets repeated across entries in a batch, and there's no `predict_answers` function for BLIP2. 

Sorry if this is a dumb question, but is a correct/reasonable way to batch this by replacing line 198 in `blip_t5.py` (`prompt = [prompt]*image.size(0)`) with a conditional that allows for prompt to be either 1) a string (as it currently works) or 2) a list (of the same length as the number of images in the batch)? 

I seem to be getting the same results on subsets I've tested, but it would be good to know if there's a more recommended way/this is silently wrong. 

```
if isinstance(prompt, str):
    prompt = [prompt]*image.size(0)
```

**Comment by LiJunnan1992** [comment]
Yes this should be a correct solution. @dxli94 we may want to implement this.

**Comment by dxli94** [comment]
Sure. I can start working on this issue.
