### ISSUE TITLE
`albef_vqa.rank_answers` returns single answer

### ISSUE THREAD

**Issue by bottledmind** [salesforce/LAVIS#11]
I've ran following piece of code
```python
import torch
from lavis.models import load_model, load_model_and_preprocess
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# load sample image
raw_image = Image.open("LAVIS/docs/_static/merlion.png").convert("RGB")

model, vis_processors, txt_processors = load_model_and_preprocess(
            name="albef_vqa", model_type="vqav2", is_eval=True, device=device
        )

question = "Which city is this photo taken?"

image = vis_processors["eval"](raw_image).unsqueeze(0).to(device)
question = txt_processors["eval"](question)

samples = {"image": image, "text_input": question}

answer_list = ["Singapore", "London", "Palo Alto", "Tokyo"]
answers = model.rank_answers(samples, answer_list=answer_list, num_ans_candidates=3)

answers
```
and got this as an output
```
{'name': 'blip_image_train', 'image_size': 384}
{'name': 'blip_image_eval', 'image_size': 384}
{'name': 'blip_question'}
{'name': 'blip_question'}

['Singapore']
```
Is this the expected behavior? Or have I missed something about the inputs? 
I was expecting 3 ordered answers or maybe even 3 ordered answers with their probabilities (would be really nice), but got the output from `predict_answers`

**Comment by bottledmind** [comment]
It would be nice if you could provide a complete description of the models' interfaces

**Comment by dxli94** [comment]
Hi @bottledmind ,

The answer is expected.

However, I see your point is valid and helpful. 

We'll discuss and see potential patch for this.

Thanks.

**Comment by phanxuanphucnd** [comment]
Hi @dxli94 
For VQA, why need answer_list for the predictive model? How to use that case without answer_list?

Thanks

**Comment by dxli94** [comment]
> Hi @dxli94 For VQA, why need answer_list for the predictive model? How to use that case without answer_list?
> 
> Thanks

Hi @phanxuanphucnd ,

Answer candidates are usually provided in VQA datasets, leading to a predictive evaluation setup.

See [example](https://github.com/salesforce/LAVIS#visual-question-answering-vqa) for cases without using answer list.

Thanks.
