### ISSUE TITLE
[Multimodal Search] COCO_train2014 dataset loading is not working.

### ISSUE THREAD

**Issue by changjinhan** [salesforce/LAVIS#110]
I've been using your streamlit demo and everything is working well except for the Multimodal Search task. I am encountering error messages, which are listed below. Can you please help me resolve this issue?

`FileNotFoundError: [Errno 2] No such file or directory: '/export/home/.cache/lavis/coco/images/train2014/COCO_train2014_000000426151.jpg'`

![image](https://user-images.githubusercontent.com/37570566/217413119-5ef9ea0e-96f6-4b74-8aaf-f21367901e89.png)

**Comment by dxli94** [comment]
Hi,

Thanks for confirming the most functions are working alright.

It seems the paths to the COCO images is hard-coded in the demo, see https://github.com/salesforce/LAVIS/blob/main/app/__init__.py#L26. Please update this to the directory where you coco image is stored on the local disk.

Thanks.

**Comment by changjinhan** [comment]
I appreciate your comment.
Following your suggestion, I updated the hard-coded cache_root in the files at
https://github.com/salesforce/LAVIS/main/app/__init__.py#L26 and https://github.com/salesforce/LAVIS/blob/main/lavis/configs/default.yaml#L10 in order to download the COCO dataset. 
This has resolved all issues. 

Thank you.
