### ISSUE TITLE
Unwanted guidance when textual content is overlaid in the image

### ISSUE THREAD

**Issue by adrielkuek** [salesforce/LAVIS#112]
Hi, was exploring with both the decoder-only and encoder-decoder models for captioning and VQA task, and I realised that the model tends to be misguided with the presence of text overlays within the image. Particularly for movie posters, infographics and even memes, the captioning or VQA outputs collapses into reproducing exactly the text content similar to OCR. This might the issue of the frozen visual encoder employing CLIP-style representation learning where it tends to extract OCR out of the box, thereby downplaying or ignoring the visual content within the image. I'm not sure whether this could be overcome through a fine-tuning of the representation learning process with images of such layouts, or rather, there is a need to relook into how the visual information can be encoded with disentanglement from textual overlays.

Just would like to hear your thoughts on this! Thank you so much.

**Comment by LiJunnan1992** [comment]
Thanks for your suggestion! We have noticed this issue as well and are investigating solutions for future model versions. This issue very likely arises from the (1) frozen visual encoder, (2) our training data which contains a lot of OCR-like texts.

**Comment by dxli94** [comment]
Closed the issue as no change is required.
