### ISSUE TITLE
Possible to reduce the VRAM usage just by 10%?

### ISSUE THREAD

**Issue by Marcophono2** [salesforce/LAVIS#118]
Hello!

I was a big fan already of BLIP (1) and very impressed by the improvement of BLIP 2. I have a RTX 4090 but unfortunatelly its VRAM is just a little bit too small for your largest checkpoint. 27 GB > 24 GB. I tested it by renting an instance with a A6000 but that's not a really good solution. :-) Is there a way to reduce the VRAM usage for the biggest model to stay below 24 GB?

Best regards
Marc

**Comment by dxli94** [comment]
The HF integration with 8bit loading may be a solution. https://huggingface.co/docs/transformers/main/en/model_doc/blip-2

This is very fresh and some changes may happen. But may help to get some preliminary idea.

**Comment by Marcophono2** [comment]
Thanks a lot, @dxli94 !

**Comment by Marcophono2** [comment]
@dxli94 I tried it out but get an error message:

```
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.8/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/marc/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
Traceback (most recent call last):
  File "/home/marc/Schreibtisch/AI/blip3.py", line 7, in <module>
    model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-flan-t5-xxl", load_in_8bit=True, device_map="auto")
  File "/home/marc/anaconda3/envs/blip/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2526, in from_pretrained
    device_map = infer_auto_device_map(
  File "/home/marc/.local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 531, in infer_auto_device_map
    tied_module_index = [i for i, (n, _) in enumerate(modules_to_treat) if n in tied_param][0]
IndexError: list index out of range
```
My code is

import torch
import requests
from PIL import Image
from transformers import Blip2Processor, Blip2ForConditionalGeneration

processor = Blip2Processor.from_pretrained("Salesforce/blip2-flan-t5-xxl")
model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-flan-t5-xxl", load_in_8bit=True, device_map="auto")


```
img_url = 'http://images.cocodataset.org/val2017/000000039769.jpg'
raw_image = Image.open(requests.get(img_url, stream=True).raw).convert('RGB')

question = "how many dogs are in the picture?"
inputs = processor(raw_image, question, return_tensors="pt").to("cuda", torch.float16)

out = model.generate(**inputs)
print(processor.decode(out[0], skip_special_tokens=True))
```

Andy idea what I did wrong?
Neither RAM nor VRAM are limited factors. (at least not until line 7 of the code... :smile: )

**Comment by Marcophono2** [comment]
@dxli94 Found it!! The most important point was to update accelerate and bitsandbytes (to ver 0.3.7). Now it works like a charme! 22 GB VRAM were used. Perfect!! 

```
import torch
import requests
from PIL import Image
from transformers import Blip2Processor, Blip2ForConditionalGeneration
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"


processor = Blip2Processor.from_pretrained("Salesforce/blip2-flan-t5-xxl", load_in_8bit=True, device_map="auto")
model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-flan-t5-xxl", load_in_8bit=True, device_map="auto")

img_url = 'http://images.cocodataset.org/val2017/000000039769.jpg'
raw_image = Image.open(requests.get(img_url, stream=True).raw).convert('RGB')

question = "what animals that are in the picture?"

inputs = processor(raw_image, question, return_tensors="pt").to(device, torch.float16)

out = model.generate(**inputs)
print(processor.decode(out[0], skip_special_tokens=True))
```
