### ISSUE TITLE
dependencies for `run_demo.sh`

### ISSUE THREAD

**Issue by bottledmind** [salesforce/LAVIS#12]
running following in an empty venv
```bash
git clone https://github.com/salesforce/LAVIS.git
cd LAVIS
pip install -e .
```
gives
![image](https://user-images.githubusercontent.com/60937565/194056360-ecc1c80a-9ab3-454f-a723-6df1cb8589e5.png)
with scipy installed via `pip install scipy` I'm getting
![image](https://user-images.githubusercontent.com/60937565/194056761-215f9049-7217-4e55-ab4b-ba5dcac118bd.png)
scikit-image installation does the trick

**Comment by dxli94** [comment]
Hi @bottledmind , please see comments in this [PR](https://github.com/salesforce/LAVIS/pull/13).

**Comment by dxli94** [comment]
Merged in this [PR](https://github.com/salesforce/LAVIS/pull/13).
