### ISSUE TITLE
Unable to install salesforce-lavis in Python 3.9.13 Jupyter notebook 

### ISSUE THREAD

**Issue by innominate-dreamer** [salesforce/LAVIS#122]
I am currently using Python 3.9.13 version 
I tried to install salesforce Lavis in Jupyter notebook using pip

**pip install salesforce-lavis**

 But I got the below error, it says that decord (from salesforce-Lavis) requires python<3.5 version.

**ERROR: Ignored the following versions that need a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement decord (from salesforce-lavis) (from versions: none)
ERROR: No matching distribution found for decord**

Could you please provide a workaround for this?

**Comment by dxli94** [comment]
Are you using MacOS?

**Comment by innominate-dreamer** [comment]
yes

**Comment by dxli94** [comment]
Can you try install from source, while removing decord from requirement.txt? 

Decord does not support recent python versions on macos https://github.com/salesforce/LAVIS/issues/15.
