### ISSUE TITLE
An error occurred while loading the blip2_feature_extractor

### ISSUE THREAD

**Issue by shy2000** [salesforce/LAVIS#128]
Thanks for the great work!
I was trying out BLIP2 feature extractor,actually it works. But when i load the model by
 `load_model_and_preprocess(name="blip2_feature_extractor", model_type="pretrain", is_eval=True, device=device)`
There're lots of missing keys.
e.g.
`Missing keys ['visual_encoder.cls_token', 'visual_encoder.pos_embed', 'visual_encoder.patch_embed.proj.weight', 'visual_encoder.patch_embed.proj.bias', 'visual_encoder.blocks.0.norm1.weight', 'visual_encoder.blocks.0.norm1.bias', 'visual_encoder.blocks.0.attn.q_bias', 'visual_encoder.blocks.0.attn.v_bias' ...`

I wonder if the pretrained model from [https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/eva_vit_g.pth](url) is incomplete or something else caused it.

**Comment by LiJunnan1992** [comment]
Hi, thanks for reporting the issue. This is not an error.
Missing keys are expected when loading pre-trained feature extractor. The "blip2_feature_extractor" checkpoint does not contain visual_encoder parameters, because the visual_encoder has been initialized from frozen eva_vit_g.

**Comment by shy2000** [comment]
So there is actually no problem, thank you for your reply
