### ISSUE TITLE
BLIP2 example code resulting in 'Killed' output

### ISSUE THREAD

**Issue by drcostco** [salesforce/LAVIS#129]

**Comment by dxli94** [comment]
What is the machine spec and model you are loading? This is most likely an OOM. Thanks.

**Comment by drcostco** [comment]
> 

Was running a linux box with 2xA100

**Comment by dxli94** [comment]
It could be RAM OOM, not VRAM.

**Comment by Theodoric008** [comment]
how much RAM is need ?
