### ISSUE TITLE
Blip2 caption result is empty

### ISSUE THREAD

**Issue by vonchenplus** [salesforce/LAVIS#132]
Thanks for your great work. 

I tested the caption of blip2 and got an empty result, here is the sample code, please tell me any wrong with it?

```
import torch
from PIL import Image
# setup device to use
device = torch.device("cuda") if torch.cuda.is_available() else "cpu"
# load sample image
raw_image = Image.open("/coderepo/LAVIS/1.png").convert("RGB")

from lavis.models import load_model_and_preprocess
# loads BLIP-2 pre-trained model
model, vis_processors, _ = load_model_and_preprocess(name="blip2_t5", model_type="caption_coco_flant5xl", is_eval=True, device=device)
# prepare the image
image = vis_processors["eval"](raw_image).unsqueeze(0).to(device)

caption = model.generate({"image": image})
print(caption)
```

Thanks.

**Comment by dxli94** [comment]
Hi @vonchenplus, what do you mean by empty here?

Is the return value is None, or is it an empty list, or it is a list of an empty string?

**Comment by vonchenplus** [comment]
> 

empty string

**Comment by dxli94** [comment]
@vonchenplus please try to pass in a prompt as input and see the difference.

`model.generate({"image": image, "prompt": "a photo of"})`

**Comment by vonchenplus** [comment]
@dxli94 Also empty string, follow output log:
```
Position interpolate from 16x16 to 26x26
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.66s/it]
['']
```

By the way, I finetune few code changed to fix runtime error, follow code changes:
Befoer:
```
        device_type = "cuda" if "cuda" in str(self.device) else "cpu"
        with torch.amp.autocast(device_type=device_type, dtype=torch.bfloat16):
            inputs_embeds = self.t5_model.encoder.embed_tokens(input_tokens.input_ids)
            inputs_embeds = torch.cat([inputs_t5, inputs_embeds], dim=1)
```
After:
```
        device_type = "cuda" if "cuda" in str(self.device) else "cpu"
        with torch.cuda.amp.autocast(dtype=torch.float16):
            inputs_embeds = self.t5_model.encoder.embed_tokens(input_tokens.input_ids)
            inputs_embeds = torch.cat([inputs_t5, inputs_embeds], dim=1)
```

**Comment by LiJunnan1992** [comment]
We used Bfloat16 for FlanT5 during BLIP-2 training, as FlanT5 has some known issues with fp16 (https://huggingface.co/google/flan-t5-xxl/discussions/9).

Therefore, `with torch.cuda.amp.autocast(dtype=torch.float16):` might be the reason for the error. If your GPU does not support bfloat16, I would recommend to use fp32.

Alternatively, you can checkout the 8-bit BLIP-2 support from HuggingFace: https://huggingface.co/docs/transformers/main/en/model_doc/blip-2

**Comment by vonchenplus** [comment]
Ok, thank you very much.
