### ISSUE TITLE
About the text split of BLIP-T5

### ISSUE THREAD

**Issue by yqy2001** [salesforce/LAVIS#139]
Thanks for the great work!

In the [forward](https://github.com/salesforce/LAVIS/blob/91500e99eea054fc4f66af2ceab873b48a3d18b8/lavis/models/blip2_models/blip2_t5.py#L126) of `Blip2T5` model, the text parts of `samples` consists of `text_input` and `text_output`, while there is no corresponding code in the dataset part to split the input text. 

Could you tell me which strategy is used to split the input text as prefix and target for prefix LM training? 
Thanks!

**Comment by LiJunnan1992** [comment]
Hi, for prefix LM pre-training, we randomly sample a split point from position 1 to the midpoint of the sequence.

**Comment by yqy2001** [comment]
Thanks.

**Comment by ylsung** [comment]
Hi @LiJunnan1992, thank you for providing the codes!

I also ran into a similar error that there is no "text_output" in the BLIP2-T5's forward function (in pre-training stage 2). Could you please show me where the random split happens? I check the dataset class (https://github.com/salesforce/LAVIS/blob/720f689559d32499980c6d14edd9959bd78d4293/lavis/datasets/datasets/image_text_pair_datasets.py#L36-L47), but there is no "text_output" stored. I also used `grep -n text_output -r lavis` and didn't find any place to create it. I appreciate any help on this. Thank you.

**Comment by ylsung** [comment]
Never mind. I solved it by adding a new dataset and builder that split the caption into two. Thanks.

**Comment by MathewCrespo** [comment]
> Never mind. I solved it by adding a new dataset and builder that split the caption into two. Thanks.

Hi, could you please show us how and how to add a new dataset and builder that split the caption? Many Thanks!

**Comment by ylsung** [comment]
In `lavis/datasets/datasets` folder, I copied the code from `image_text_pair_datasets.py` to a new file `prefix_language_pretraining.py`, and added a new class

```python

class PrefixLanguagePretrainingDataset(BaseDataset, __DisplMixin):
    def __init__(self, vis_processor, text_processor, vis_root, ann_paths):
        """
        vis_root (string): Root directory of images (e.g. coco/images/)
        ann_root (string): directory to store the annotation file
        """
        super().__init__(vis_processor, text_processor, vis_root, ann_paths)

    def __getitem__(self, index):

        # TODO this assumes image input, not general enough
        ann = self.annotation[index]

        image_path = os.path.join(self.vis_root, ann["image"])
        image = Image.open(image_path).convert("RGB")

        image = self.vis_processor(image)
        caption = self.text_processor(ann["caption"])

        split = random.randint(1, len(caption) // 2)

        prefix = caption[:split]
        output = caption[split:]

        return {"image": image, "text_input": prefix, "text_output": output}

```

In `lavis/datasets/builders`, I also added a new class

```python

import os
from lavis.common.registry import registry

from lavis.datasets.builders.base_dataset_builder import BaseDatasetBuilder
from lavis.datasets.datasets.prefix_language_pretraining import PrefixLanguagePretrainingDataset
from lavis.datasets.datasets.laion_dataset import LaionDataset


@registry.register_builder("prefix_conceptual_caption_3m")
class PrefixConceptualCaption3MBuilder(BaseDatasetBuilder):
    train_dataset_cls = PrefixLanguagePretrainingDataset

    DATASET_CONFIG_DICT = {
        "default": "configs/datasets/prefix_conceptual_caption/defaults_3m.yaml"
    }
```

The other two things needed to be taken care of are: (1) updating `lavis/datasets/builders/__init__.py` (2) adding the config for the new class in  `lavis/configs/datasets`. You can do that by copying the codes/folders for image-text pairs.

**Comment by MathewCrespo** [comment]
> In `lavis/datasets/datasets` folder, I copied the code from `image_text_pair_datasets.py` to a new file `prefix_language_pretraining.py`, and added a new class
> 
> ```python
> class PrefixLanguagePretrainingDataset(BaseDataset, __DisplMixin):
>     def __init__(self, vis_processor, text_processor, vis_root, ann_paths):
>         """
>         vis_root (string): Root directory of images (e.g. coco/images/)
>         ann_root (string): directory to store the annotation file
>         """
>         super().__init__(vis_processor, text_processor, vis_root, ann_paths)
> 
>     def __getitem__(self, index):
> 
>         # TODO this assumes image input, not general enough
>         ann = self.annotation[index]
> 
>         image_path = os.path.join(self.vis_root, ann["image"])
>         image = Image.open(image_path).convert("RGB")
> 
>         image = self.vis_processor(image)
>         caption = self.text_processor(ann["caption"])
> 
>         split = random.randint(1, len(caption) // 2)
> 
>         prefix = caption[:split]
>         output = caption[split:]
> 
>         return {"image": image, "text_input": prefix, "text_output": output}
> ```
> 
> In `lavis/datasets/builders`, I also added a new class
> 
> ```python
> import os
> from lavis.common.registry import registry
> 
> from lavis.datasets.builders.base_dataset_builder import BaseDatasetBuilder
> from lavis.datasets.datasets.prefix_language_pretraining import PrefixLanguagePretrainingDataset
> from lavis.datasets.datasets.laion_dataset import LaionDataset
> 
> 
> @registry.register_builder("prefix_conceptual_caption_3m")
> class PrefixConceptualCaption3MBuilder(BaseDatasetBuilder):
>     train_dataset_cls = PrefixLanguagePretrainingDataset
> 
>     DATASET_CONFIG_DICT = {
>         "default": "configs/datasets/prefix_conceptual_caption/defaults_3m.yaml"
>     }
> ```
> 
> The other two things needed to be taken care of are: (1) updating `lavis/datasets/builders/__init__.py` (2) adding the config for the new class in `lavis/configs/datasets`. You can do that by copying the codes/folders for image-text pairs.

Very helpful instructions! Appreciate ur help!

**Comment by ankitkv** [comment]
Should this splitting be done in the raw text or on the tokens? If the raw text split breaks a set of characters that should have otherwise been a single token, we introduce new tokens that are not really part of the data distribution. Does this noise hamper training? @LiJunnan1992 Can you please clarify if you do the split in raw text or in the tokenized sequences? Thank you!
