### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by arfizato** [salesforce/LAVIS#140]
Hello, Great work to all contributors. I tried installing this on my WIN10 laptop but got this error tried installing it on a VM running fedora 37 same problem. but works fine on google collabs
`ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement torchvision (from salesforce-lavis) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3)
ERROR: No matching distribution found for torchvision`

saw on #13 and tried using the requirements.txt he provided but still doesn't work.
Tried both the pip install method and the git method none worked. 
Do I have to revert to python <3.5  ?

**Comment by dxli94** [comment]
Can you try updating your pytorch version before installing torchvision?
