### ISSUE TITLE
[Issue] RuntimeError: The size of tensor a (3) must match the size of tensor b (9) at non-singleton dimension 0

### ISSUE THREAD

**Issue by AnaRhisT94** [salesforce/LAVIS#142]
Hi,

Getting this error when using the code from `examples/blip2-caption`: 
`RuntimeError: The size of tensor a (3) must match the size of tensor b (9) at non-singleton dimension 0`

But the nucleus sampling works: `self.model.generate({"image": image}, use_nucleus_sampling=True)`

```
import os
from pathlib import Path
import wget
from lavis.models import load_model_and_preprocess
# import flopth

class BLIP_Captioner():

    def __init__(self):
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.model, self.vis_processors, _ = load_model_and_preprocess(
        name="blip_caption", model_type="large_coco", is_eval=True, device=self.device
        )
    
    def generate_caption(self, image):

        with torch.no_grad():
            image = self.vis_processors["eval"](image).unsqueeze(0).to(self.device)
            self.model.generate({"image": image})
    

def main():

    blip_instance = BLIP_Captioner()

    img_url = 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/demo.jpg' 
    raw_image = Image.open(requests.get(img_url, stream=True).raw).convert('RGB')

    blip_instance.generate_caption(raw_image)

if __name__ == '__main__':
    main()
```

**Comment by tonyf** [comment]
Getting this as well. Only works if I disable beam search

**Comment by LiJunnan1992** [comment]
Can I know your transformer version? Could you try to use version 4.25.0?

**Comment by dxli94** [comment]
@AnaRhisT94 Can you please clarify which model you are using? You mentioned it is "blip2_caption" but the model loaded is "blip_caption".

**Comment by AnaRhisT94** [comment]
@dxli94  You are right, I'll be using Hugging Face caption for Blip2 now.

**Comment by DevNullx64** [comment]
> Can I know your transformer version? Could you try to use version 4.25.0?
@LiJunnan1992 
This work in my case.

I using WLS 2, and run_demo.sh to test.
With transformers >= 4.28.0 it not work when using Image Decription Generation with model BLIP_base and Bean search. It output "RuntimeError: The size of tensor a (3) must match the size of tensor b (9) at non-singleton dimension 0". With transformers == 4.25.0, pip is not rely happy about the dépendancy break. But it wotk.

> Getting this as well. Only works if I disable beam search
@tonyf it also work.

**Comment by kcarolan96** [comment]
> Getting this as well. Only works if I disable beam search

how did you disable beam search?
