### ISSUE TITLE
Run out of RAM on Google Colab Pro

### ISSUE THREAD

**Issue by kosmicdream** [salesforce/LAVIS#144]
Even with 25.5GB of RAM, my Colab instance of blip2_instructed_generation runs out when loading the model.

How much RAM do I need? I was under the impression that 25.5 was the maximum Colab offers.

**Comment by kosmicdream** [comment]
Turns out that to get more RAM out of Colab, you have to select both the high RAM option and the premium GPU class one. The model takes about 51GB of RAM to load

**Comment by xxiMiaxx** [comment]
issue still persists even with the aforementioned details  :(
