### ISSUE TITLE
How to handle multiple images with Blip2 models ?

### ISSUE THREAD

**Issue by rr191211** [salesforce/LAVIS#148]
How to handle multiple images with Blip2 models?  I have a large number of questions which require more than one image to answer for VQA task, like 1 questions vs image set. Can I extracting the features from each image in my image set and then concat them as input to the Qformer? Thx.

**Comment by 1TTT9** [comment]
Hello,  Sorry, I know this issue has been closed. However, may I ask how you cope with two or more images as inputs for visual QA with BLIP-2? Any public codes or tips would be appreciated. Thanks.
