### ISSUE TITLE
BLIP captioning min_length and max_length ?

### ISSUE THREAD

**Issue by key88sf** [salesforce/LAVIS#150]
Does the `generate()` function still take arguments for `min_length` and `max_length` ? I'm passing those and not seeing any difference in the generated captions:

e.g. `model.generate({"image": image}, min_length=5, max_length=16)`

**Comment by LiJunnan1992** [comment]
The BLIP captioning model takes that argument: https://github.com/salesforce/LAVIS/blob/1a0c1e37cf4ec783aa9bcb35bc58e50e9a7e777c/lavis/models/blip_models/blip_caption.py#L196

Could you please provide an example of your issue?

**Comment by LiJunnan1992** [comment]
the max_length refers to the number of tokens not chars.

**Comment by key88sf** [comment]
Aha, thank you. 👍
