### ISSUE TITLE
blip2 hardware requirements

### ISSUE THREAD

**Issue by jacobzlogar** [salesforce/LAVIS#151]
Hi, thanks for the library/associated models
I'm trying to use `blip2_opt` with the `opt6.7b` model type on a `n1-highmem-8` instance (8 cores, 52gb ram) with 1 nvidia v100 (16gb) - the instance uses all 16gb of the gpu's memory and crashes afterwards when calling inference with the following.
```
        @self.post("/blip2-inference")
        async def blipv2(url: str, text: str):
            device = torch.device("cuda")
            print(torch.cuda.is_available())
            raw_image = Image.open(requests.get(url, stream=True).raw).convert("RGB")
            model, vis_processors, _ = load_model_and_preprocess(
                name="blip2_opt",
                model_type="pretrain_opt6.7b",
                is_eval=True,
                device=device,
            )
            image = vis_processors["eval"](raw_image).unsqueeze(0).to(device)
            return model.generate({"image": image, "prompt": text})
```

Is more than 16gb of gpu memory required?

**Comment by jacobzlogar** [comment]
so seems like the 2.7b param model is using 9.8gb of gpu memory, i guess that means i need > 16gb gpu memory to run the 6.7b param model

**Comment by FayZ676** [comment]
Did you ever figure out exactly how much VRAM opt-6.7 requires?

**Comment by jacobzlogar** [comment]
i think i was able to run it on an a10 instance (24gb)

**Comment by jacobzlogar** [comment]
but maybe possible with less gram using half precision?

**Comment by FayZ676** [comment]
Sick, thanks for the clarification
