### ISSUE TITLE
How to download the synthesized data of BLIP-2?

### ISSUE THREAD

**Issue by mxin262** [salesforce/LAVIS#155]
Hi, Thanks for your job. Can you provide the download link for the synthetic data of BLIP-2? How is this data used? Is there a code for it?

**Comment by dxli94** [comment]
Unfortunately we don't have a straightforward way to share the data at this stage.

However, we may be able to provide a script for capfilt with BLIP and CLIP when we got time.

**Comment by mxin262** [comment]
Thanks.
