### ISSUE TITLE
lemmatize of OKVQA

### ISSUE THREAD

**Issue by Richar-Du** [salesforce/LAVIS#156]
I notice that you add a step to lemmatize the prediction of OKVQA in blip-2, which may affect the performance. The accuracy before and after lemmatizing is 35 and 40. However, the predictions of previous baselines are not lemmatized. Should we lemmatize them to make a fair comparison?

Thanks in advance.

**Comment by LiJunnan1992** [comment]
Hi, thanks for your question. We noticed that the ground-truth answers of OKVQA have been lemmatized, hence we perform lemmatization to truthfully reflect the zero-shot performance of BLIP-2. We are not sure whether previous baselines perform this step and whether it is useful to them. We encourage future methods to perform lemmatization for fair comparisons.

**Comment by Richar-Du** [comment]
Got it! Thanks for your explanation :)
