### ISSUE TITLE
Are the BLIP2 released models based on eva vit-g instead of clip vit-l?

### ISSUE THREAD

**Issue by evelinehong** [salesforce/LAVIS#159]
Are all the BLIP2 models based on eva-clip vit-g?
Also, what are the output feature dimension of vit-g and vit-l?

**Comment by LiJunnan1992** [comment]
Yes they are based on eva-clip ViT-g with 1408 output dimension. The output dimension for ViT-large is 1024.

**Comment by evelinehong** [comment]
Do you plan to release other models based on clip with 512/768 output dimension?

**Comment by LiJunnan1992** [comment]
We do not have such plans now.

**Comment by evelinehong** [comment]
thank you
