### ISSUE TITLE
Question about blip vqa

### ISSUE THREAD

**Issue by sjh960123** [salesforce/LAVIS#16]
hello

First of all, thank you for building such a wonderful library.

I have a question about VQA using BLIP.

It is about samples among the arguments of predict_answers in BLIP VQA model.

samples (dict): A dictionary containing the following keys:
                - image (torch.Tensor): A tensor of shape (batch_size, 3, H, W). Default H=480, W=480.
                - text_input (list): A list of strings, each string is a question

In the case of text_input, it is a list format, and I think I can put multiple questions.

However, when I put several questions in the list and ran it, I got a tensor size mismatch error.

I want to know if the VQA is running only one question per image.

thanks

**Comment by dxli94** [comment]
Hi @sjh960123 ,

Thanks for raising the issue. We've now updated the comments to make it clear that the number of questions is expected to be the same as the number of images (or batch size). See the referenced commits for detail.

In case you want to ask more questions about the same image, you may repeat the image along the batch size dimension. Kindly find the code snippet below for reference:
```
import torch
from PIL import Image
# setup device to use
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# load sample image
raw_image = Image.open("docs/_static/merlion.png").convert("RGB")

from lavis.models import load_model_and_preprocess
model, vis_processors, txt_processors = load_model_and_preprocess(name="blip_vqa", model_type="vqav2", is_eval=True, device=device)
# ask a random question.
question = "Which city is this photo taken?"
image = vis_processors["eval"](raw_image).unsqueeze(0).to(device)
question = txt_processors["eval"](question)

bz = 2
image = image.repeat(bz, 1, 1, 1)
question_list = [question] * bz 

model.predict_answers(samples={"image": image, "text_input": question_list}, inference_method="generate")
# ['singapore', 'singapore']
```
