### ISSUE TITLE
RuntimeError when running on CPU

### ISSUE THREAD

**Issue by jose-alanaai** [salesforce/LAVIS#162]
When running the examples from the [colab](https://colab.research.google.com/github/salesforce/LAVIS/blob/main/examples/blip2_instructed_generation.ipynb), they work fine on GPU but I get the following runtime error when trying to run on CPU:

```sh
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.HalfTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```

Below is a snippet of code to reproduce the error:

```python
import torch
import requests

from PIL import Image
from lavis.models import load_model_and_preprocess

device = torch.device('cpu')
with torch.inference_mode():
    model, vis_processors, _ = load_model_and_preprocess(
        name='blip2_t5',
        model_type='pretrain_flant5xl',
        is_eval=True,
        device=device
    )

img_url = 'https://storage.googleapis.com/sfr-vision-language-research/LAVIS/assets/merlion.png'
raw_image = Image.open(requests.get(img_url, stream=True).raw).convert('RGB')
image = vis_processors["eval"](raw_image).unsqueeze(0).to(device)

model.generate({"image": image, "prompt": "Question: which city is this? Answer:"})
```

I'm wondering whether this is due to some version mismatch between any of the libraries or whether perhaps there is somewhere in the code where the `device` is being ignored? The versions of `torch` and `transformers` are as follows:

```sh
torch                    1.12.1+cu113
torchvision              0.13.1+cu113
transformers             4.26.1
```

P.S.: This issue is similar to https://github.com/salesforce/LAVIS/issues/145 but the opposite behaviour...

**Comment by jose-alanaai** [comment]
UPDATE: When I got the previous error, I had installed the latest release available of `salesforce-lavis` which was `1.0.0`. Now, I have installed from source and the error has shifted to the following:

```sh
RuntimeError: Input type (float) and bias type (c10::Half) should be the same
```

The versions of the relevant libs are the following:

```sh
salesforce-lavis         1.0.1
torch                    1.13.1
torchvision              0.14.1
transformers             4.26.1
```

**Comment by LiJunnan1992** [comment]
Hi, instead of `device = torch.device('cpu')`, could you use `device='cpu' `instead? It should solve this problem.

**Comment by jose-alanaai** [comment]
Hi @LiJunnan1992, thank you very much! That fixed it!

**Comment by dxli94** [comment]
With https://github.com/salesforce/LAVIS/commit/baad2d7c8df599d8d9b081ba2e946626eaa2dc34, this issue should now be fixed.
