### ISSUE TITLE
BLIP and BLIP2 model details

### ISSUE THREAD

**Issue by jonathan-roberts1** [salesforce/LAVIS#164]
Great work! Thanks for releasing the models, pre-trained checkpoints and examples.

I have a couple of questions about the BLIP and BLIP 2 models - I can't clearly find this info in the papers/repo but apologies if I've missed it.

1. For the ‘base’ BLIP feature extractor:
    a. How many images were used during pretraining (is it the 14M or 129M version)?
    b. Is this the ViT-B/16 vision transformer version?
2. For the ‘pretrain’ and ‘coco’ BLIP 2 feature extractors:
    a. Which image encoder was used? (I’m assuming ViT-L or ViT-G)
    b. Roughly, how many images were used during the COCO fine-tuning?

Thanks!

**Comment by LiJunnan1992** [comment]
Thanks for your questions. Here are my answers.

1.a. It is the 129M version
1.b. Yes
2.a. We use ViT-g for all BLIP-2 models
2.b. We use coco-karpathy-train with 113K images.

Hope this helps.

**Comment by jonathan-roberts1** [comment]
Perfect, thanks!
