### ISSUE TITLE
Would you release the weights for the BLIP2 ViT-L version?

### ISSUE THREAD

**Issue by Kamino666** [salesforce/LAVIS#165]
Thank you for your fantastic work! Would you release the weights for the BLIP2 ViT-L version?

**Comment by LiJunnan1992** [comment]
Yes we have just released the pretrained VIT-L weights in #169

**Comment by Domogro** [comment]
> Yes we have just released the pretrained VIT-L weights in #169

@LiJunnan1992 Which is the difference between blip2_pretrained_vitL.pth and blip2_pretrained_flant5xl_vitL.pth
