### ISSUE TITLE
Which distributed training library is used for training BLIP2?

### ISSUE THREAD

**Issue by yqy2001** [salesforce/LAVIS#166]
Hi, thanks for the great work again! Could you share which library (_e.g._ `DeepSpeed`, `FairScale`) you used to assist the distributed training of BLIP-2, or just `PyTorch DDP`?

Thanks!

**Comment by dxli94** [comment]
PyTorch DDP was mainly used.

Thanks.

**Comment by yqy2001** [comment]
Thank you.
