### ISSUE TITLE
Confidence of the BLIP captioning model

### ISSUE THREAD

**Issue by jhwang7628** [salesforce/LAVIS#17]
Hi, 

Is there a way to access the confidence of the generated caption?

**Comment by karndeepsingh** [comment]
> Hi,
> 
> Is there a way to access the confidence of the generated caption?

@jhwang7628 I have a similar question. Did you figure out any way to get the confidence level?

**Comment by dxli94** [comment]
Hi @jhwang7628 @karndeepsingh 

Currently this is not natively supported. I have to look into whether this is possible for HF bert.

One alternative might be to forward the generated caption and the original image into the BLIP ITM model to get a matching score.

Thanks.

**Comment by karndeepsingh** [comment]
> Hi @jhwang7628 @karndeepsingh
> 
> Currently this is not natively supported. I have to look into whether this is possible for HF bert. This expects delay.
> 
> One alternative might be to forward the generated caption and the original image into the BLIP ITM model to get a matching score.
> 
> Thanks.

Thanks @dxli94 for answering. 
How can i get confidence score for VQA using BLIP? 
Also, How I can compare the results of VQA and report the accuracy of the model on my dataset ( I am only using pre-trained model for now)?

**Comment by karndeepsingh** [comment]
> Hi @jhwang7628 @karndeepsingh
> 
> Currently this is not natively supported. I have to look into whether this is possible for HF bert. This expects delay.
> 
> One alternative might be to forward the generated caption and the original image into the BLIP ITM model to get a matching score.
> 
> Thanks.

@dxli94 How i can use BLIP ITM on text and image to predict the confidence? Any resource or notebook can you share? Is it possible using lavis ?
