### ISSUE TITLE
Stage2-Pretraining for FlanT5-XL

### ISSUE THREAD

**Issue by waxnkw** [salesforce/LAVIS#174]
I am trying to conduct a stage2-pretraining for FlanT5-XL. But, I see that BLIP2-FlanT5 forward function requires to use both `samples['text_input']` and `samples['text_output']`. I am curious about what should `samples['text_input']` and `samples['text_input']` be for stage2-pretraining. Are they the following format:

    samples['text_input']: empty string
    samples['text_output']: image caption

**Comment by dxli94** [comment]
See https://github.com/salesforce/LAVIS/issues/139 for reference.

**Comment by waxnkw** [comment]
Thanks
