### ISSUE TITLE
Key Error: "text_output"

### ISSUE THREAD

**Issue by Richar-Du** [salesforce/LAVIS#181]
When I run run_scripts/blip2/train/pretrain_stage2.sh, there raises an error in https://github.com/salesforce/LAVIS/blob/baad2d7c8df599d8d9b081ba2e946626eaa2dc34/lavis/models/blip2_models/blip2_t5.py#L131
because there is not a key called "text_output".

**Comment by vanpersie32** [comment]
same question here

**Comment by LiJunnan1992** [comment]
Please see https://github.com/salesforce/LAVIS/issues/139.

Thanks.
