### ISSUE TITLE
Got Bleu_4: 41.9 and CIDEr: 143.9 rather than 42.4 and 144.5 using Salesforce/blip2-flan-t5-xl-coco

### ISSUE THREAD

**Issue by xszheng2020** [salesforce/LAVIS#182]
Hi, @LiJunnan1992, thanks for your work.
I am trying to replicate the results in Table 3.
I loaded blip2-flan-t5-xl-coco and called the generate function using the following hyper-parameters, the random seed is 42.
But I got Bleu_4: 41.9 and CIDEr: 143.9 on the coco test split.
Any idea? Thanks!

``` 
generated_ids = model.generate(**inputs, 
                               do_sample=False,
                               max_length=30,
                               min_length=8,
                               num_beams=5,
                              )
```

```
Bleu_1: 0.826
Bleu_2: 0.682
Bleu_3: 0.541
Bleu_4: 0.419
METEOR: 0.317
ROUGE_L: 0.616
CIDEr: 1.439
SPICE: 0.257
```

**Comment by SangbumChoi** [comment]
@xszheng2020 I think they did not fully released the training/evaluation pipeline of blip-flan-t5 related architecture

**Comment by xszheng2020** [comment]
@SangbumChoi  oh thanks

**Comment by linzhiqiu** [comment]
> And btw, this file is empty https://github.com/salesforce/LAVIS/blob/main/lavis/projects/blip2/eval/caption_coco_flant5xl_eval.yaml

Why is this file empty?
