### ISSUE TITLE
The default download location

### ISSUE THREAD

**Issue by baiyuyu** [salesforce/LAVIS#183]
Hey, I am try to use blip2 on a distributed computer. and I am sure there is enough disk space(200GB) under my folder, but when I run model, vis_processors, _ = load_model_and_preprocess(
    name="blip2_t5", model_type="pretrain_flant5xxl", is_eval=True, device=device
)
It told me there is not enough disk space.
I want to know which folder this model download to? I also already change the location in  Lavis/config/default.yaml.

**Comment by dxli94** [comment]
The FlanT5 model is downloaded from huggingface. Please check locations as documented here https://huggingface.co/docs/datasets/cache.

**Comment by baiyuyu** [comment]
Hey, this is for dataset file, I was trying to figure out the default location for model file.

**Comment by dxli94** [comment]
https://huggingface.co/transformers/v4.0.1/installation.html#:~:text=So%20if%20you%20don't,cache%2Fhuggingface%2Ftransformers%2F%20.

**Comment by benzzhang** [comment]
if you want to change the location, you can modify environment variables :
`vim /root/.bashrc`
add
`export TORCH_HOME="xx/xx/xx"`
`export TRANSFORMERS_CHACHE="xx/xx/xx"`
then
`source /root/.bashrc`

the default path are `~/.torch/models/` & `~/.cache/huggingface/transformers/`
