### ISSUE TITLE
Loading ALBEF feature extractor 

### ISSUE THREAD

**Issue by cs20s030** [salesforce/LAVIS#2]
while loading ALBEF feature extractor using 
model, vis_processors, text_processors = load_model_and_preprocess(name="albef_feature_extractor", model_type="base", is_eval=True, device=device)
It is returning:-
reshape position embedding from 256 to 196
None
{'name': 'blip_image_eval', 'image_size': 224}
None
{'name': 'blip_caption'}
Is this BLIP model or ALBEF ?

**Comment by dxli94** [comment]
It is ALBEF, just shares the processors with BLIP.

Thanks!

**Comment by cs20s030** [comment]
Great thanks
