### ISSUE TITLE
blip_vqa.ipynb demo have shape error during runtime

### ISSUE THREAD

**Issue by HuangChiEn** [salesforce/LAVIS#222]
As the title, the https://github.com/salesforce/LAVIS/blob/main/examples/blip_vqa.ipynb have shape problem 
![image](https://user-images.githubusercontent.com/52521165/228422611-a15dba7e-fb3b-4d7a-a49a-3418943a7fb7.png)

**Comment by dxli94** [comment]
Certain transformer version causes this issue.

Can you report your transformer version? Can you update the library and retry?

**Comment by HuangChiEn** [comment]
> Certain transformer version causes this issue.
> 
> Can you report your transformer version? Can you update the library and retry?

Thanks for your rapid reply, my previous version is `transformer==4.27.3` which is beyond the requirement.txt spec (it should be in range 4.25.0>= and <4.27). 

I have downgrade to 4.25.0 and then it works perfectly now ~

**Comment by dxli94** [comment]
Thanks for letting us know.
