### ISSUE TITLE
TypeError: Cannot interpret 'torch.float32' as a data type

### ISSUE THREAD

**Issue by onefish51** [salesforce/LAVIS#223]
when I tested `examples/blip2_instructed_generation.ipynb` a error occurred :
```
avg_gradcam = getAttMap(norm_img, gradcam[0][1], blur=True)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/lavis/common/gradcam.py", line 11, in getAttMap
    attMap = skimage_transform.resize(attMap, (img.shape[:2]), order=3, mode="constant")
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/skimage/transform/_warps.py", line 154, in resize
    not (np.issubdtype(input_type, np.integer) and order == 0) and
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/numpy/core/numerictypes.py", line 416, in issubdtype
    arg1 = dtype(arg1).type
TypeError: Cannot interpret 'torch.float32' as a data type
```

**Comment by dxli94** [comment]
Seems to be a pytorch-related issue: https://github.com/pytorch/pytorch/issues/2246.

**Comment by QinHsiu** [comment]
try to transformer the data to numpy, works fine.

**Comment by LKJ-np** [comment]
> 通过以下方式修复它：
> 
> ```
> gradcam_np = gradcam[0][1].numpy().astype(np.float32)
> avg_gradcam = getAttMap(norm_img, gradcam_np, blur=True)
> ```

resized_img = raw_image.resize((int(w * scaling_factor), int(h * scaling_factor)))
norm_img = np.float32(resized_img) / 255
gradcam = samples['gradcams'].reshape(24,24)

avg_gradcam = getAttMap(norm_img, gradcam, blur=True)
An error is also reported here, why?
Connot interpret 'torch.float32' as a data type
