### ISSUE TITLE
！？samples["text_output"] in training of BLIP2_flan_pretrain_stage2

### ISSUE THREAD

**Issue by Bazinga699** [salesforce/LAVIS#229]
![image](https://user-images.githubusercontent.com/43492238/229017598-a20120fc-4592-4cc3-a301-c61080d5504d.png)
In the training of encoder-decoder-based LLM（e.g. FlanT5）, Prefix Text(i.e. sample[‘text_input] in code) and Suffix Text(i.e. sample['text_output'] in code) are needed. However, all the datasets in this repo don't have the 'text_output', I have absolutely no idea how this division mentioned in the paper is done. I will appreciate it if author can clarify this for me, thanks!

**Comment by dxli94** [comment]
See https://github.com/salesforce/LAVIS/issues/139.

Thanks.

**Comment by Bazinga699** [comment]
> 
Ok, thanks.
