### ISSUE TITLE
annotation urls for CC, SBU

### ISSUE THREAD

**Issue by happywu** [salesforce/LAVIS#24]
Hi, 

I was trying to download the datasets, after running the download scripts for CC,
when loading CC, it failed, errors as below

when I run below code

```
from lavis.datasets.builders import load_dataset

In [3]: data = load_dataset('conceptual_caption_12m') `
```

errors as

```
File ~/anaconda3/envs/lavis/lib/python3.8/urllib/request.py:383, in Request._parse(self)
    381 self.type, rest = _splittype(self._full_url)
    382 if self.type is None:
--> 383     raise ValueError("unknown url type: %r" % self.full_url)
    384 self.host, self.selector = _splithost(rest)
    385 if self.host:

ValueError: unknown url type: '/export/home/workspace/datasets/cc12m.json'
```

same goes for 'sbu_caption', can not find url ''/export/share/dongxuli/data/lavis/sbu/annotation/sbu.json',

can you please help with obtaining these annotation json files?

Best

**Comment by happywu** [comment]
also the image loading process seems not adapting to the path defined in lavis/configs/default.yaml, the provided annotation json file for visual genome uses image location of '/export/xxxx', which will cause error when loading images

**Comment by dxli94** [comment]
Hi @happywu , thanks for raising the issue.

We have now updated the SBU annotation URL, see [commit](8422d995c91031d49309d268706deb8cf4ba5798) for information.

For conceptual captions, there are usually a missing portion of data during downloading. Therefore, our annotations will not be universally applicable. You may instead use the following scripts to generate your annotations and modify the configuration files with the annotation path accordingly.

- `lavis/datasets/download_scripts/DownloadConceptualCaptions/create_annotation_3m.ipynb`
- `lavis/datasets/download_scripts/DownloadConceptualCaptions/create_annotation_12m.ipynb`

Let us know how it works.

Thanks.

**Comment by happywu** [comment]
Thanks for updating the url and guidance for generating CC annotations!
