### ISSUE TITLE
 How to reproduce stage1 pretraining ?

### ISSUE THREAD

**Issue by Youngluc** [salesforce/LAVIS#257]
It seems that the default setting always loads a pretrained stage1 model checkpoint ? 
I am not sure that if the code contains the implementation of stage1 pretraining? From my perspective, it is necessary to modify the code to support training from scratch. Right?

**Comment by Youngluc** [comment]
Another question: 
"https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_vitL.pth", and blip2_pretrained.pth, Are they the stage1 pretraining model ckpts?

**Comment by dantengdekaoya** [comment]
> It seems that the default setting always loads a pretrained stage1 model checkpoint ? I am not sure that if the code contains the implementation of stage1 pretraining? From my perspective, it is necessary to modify the code to support training from scratch. Right?

hi, i want to ask have you reproduce stage1 on blip2? i follow the run_script 
python -m torch.distributed.run --nproc_per_node=16 train.py --cfg-path lavis/projects/blip2/train/pretrain_stage1.yaml was told 
 The specified path /mnt/workspace/workgroup/LAVIS/lavis/../export/home/.cache/lavis/vg/images/ for visual inputs does not exist.
                Please provide a correct path to the visual inputs or
                refer to datasets/download_scripts/README.md for downloading instructions.

UserWarning: storage path /mnt/workspace/workgroup/LAVIS/lavis/../export/home/.cache/lavis/vg/images/ does not exist.
  warnings.warn("storage path {} does not exist.".format(vis_path))

do i have to download this image at first ?

**Comment by LiJunnan1992** [comment]
@Youngluc You could run BLIP-2 stage 1 pre-training now with `bash run_scripts/blip2/train/pretrain_stage1.sh`

**Comment by LiJunnan1992** [comment]
> Another question: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_vitL.pth", and blip2_pretrained.pth, Are they the stage1 pretraining model ckpts?

Yes they are.

**Comment by LiJunnan1992** [comment]
> > It seems that the default setting always loads a pretrained stage1 model checkpoint ? I am not sure that if the code contains the implementation of stage1 pretraining? From my perspective, it is necessary to modify the code to support training from scratch. Right?
> 
> hi, i want to ask have you reproduce stage1 on blip2? i follow the run_script python -m torch.distributed.run --nproc_per_node=16 train.py --cfg-path lavis/projects/blip2/train/pretrain_stage1.yaml was told The specified path /mnt/workspace/workgroup/LAVIS/lavis/../export/home/.cache/lavis/vg/images/ for visual inputs does not exist. Please provide a correct path to the visual inputs or refer to datasets/download_scripts/README.md for downloading instructions.
> 
> UserWarning: storage path /mnt/workspace/workgroup/LAVIS/lavis/../export/home/.cache/lavis/vg/images/ does not exist. warnings.warn("storage path {} does not exist.".format(vis_path))
> 
> do i have to download this image at first ?

Yes please prepare the images following the documentation of LAVIS and set the path accordingly.

**Comment by Youngluc** [comment]
> @Youngluc You could run BLIP-2 stage 1 pre-training now with `bash run_scripts/blip2/train/pretrain_stage1.sh`

Thanks a lot! Nice job!!!!!!

**Comment by Youngluc** [comment]
> @Youngluc You could run BLIP-2 stage 1 pre-training now with `bash run_scripts/blip2/train/pretrain_stage1.sh`

Thanks a lot! Nice job!!!

**Comment by Youngluc** [comment]
Been Solved

**Comment by yangmengmeng123** [comment]
> > Another question: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_vitL.pth", and blip2_pretrained.pth, Are they the stage1 pretraining model ckpts?
> 
> Yes they are.

Hello, the configuration file of blip2 contains pretrain_stage1.yaml and pretrain_stage2.yaml. In your reply, blip2_pretrained_vitL.pth and blip2_pretrained.pth are ckpts of stage1, but there is no configuration of checkpoint in pretrain_stage1.yaml. So do I need to import ckpts when using pretrain_stage1.yaml
