### ISSUE TITLE
reproduce stage1 on blip2 visual inputs does not exist

### ISSUE THREAD

**Issue by dantengdekaoya** [salesforce/LAVIS#263]
hi, i want to ask how to reproduce stage1 on blip2? i follow the run_script
python -m torch.distributed.run --nproc_per_node=16 train.py --cfg-path lavis/projects/blip2/train/pretrain_stage1.yaml was told
The specified path /mnt/workspace/workgroup/LAVIS/lavis/../export/home/.cache/lavis/vg/images/ for visual inputs does not exist.
Please provide a correct path to the visual inputs or
refer to datasets/download_scripts/README.md for downloading instructions.

UserWarning: storage path /mnt/workspace/workgroup/LAVIS/lavis/../export/home/.cache/lavis/vg/images/ does not exist.
warnings.warn("storage path {} does not exist.".format(vis_path))

do i have to download this image at first ? , and i can't find datasets/download_scripts/README.md follow the path.

**Comment by xingenju** [comment]
Yes,  you should download the images at first, the download script file can be found in the folder: lavis/datasets/download_scripts/download_xx.py
