### ISSUE TITLE
Running LAVIS model locally without downloading it every time

### ISSUE THREAD

**Issue by rebecasgo** [salesforce/LAVIS#264]
What are the steps for running a LAVIS model locally (BLIP), without the need of downloading it every time?

Which folder is it downloaded to?

**Comment by rebecasgo** [comment]
The model's checkpoints are downloaded into: ~/.cache/torch/hub/checkpoints/

When running a cluster in Databricks, etc, this folder is deleted.

When run locally, it will be persisted in memory. Alternatively, we can have copies in any other folder.

Closing issue.

**Comment by dxli94** [comment]
@rebecasgo thanks. Your understanding is precisely correct. Closing the issue now.
