### ISSUE TITLE
use_dist_eval_sampler arguments in retrieval evaluation

### ISSUE THREAD

**Issue by vanpersie32** [salesforce/LAVIS#270]
When I set use_dist_eval_sampler=True in retrieval evaluation, the result is very bad. But when I set use_dist_eval_sampler False, the result is very good

**Comment by dxli94** [comment]
use_dist_eval_sampler must be set to True for evaluation of retrieval. This is due to the way we split the computation across nodes - not all nodes do the same computation.

**Comment by vanpersie32** [comment]
> use_dist_eval_sampler must be set to True for evaluation of retrieval. This is due to the way we split the computation across nodes - not all nodes do the same computation.

Thanks for your reply. The use_dist_eval_sample is set to False
https://github.com/salesforce/LAVIS/blob/b1817a0cb27f137b0d5d06f1c904efbb573c670e/lavis/projects/blip2/eval/ret_coco_eval.yaml#L45

**Comment by vanpersie32** [comment]
> use_dist_eval_sampler must be set to True for evaluation of retrieval. This is due to the way we split the computation across nodes - not all nodes do the same computation.

You seem to say the opposite. We must set use_dist_eval_sampler to False for evaluation of retrieval. Anyway, thanks for you code and kindly reply

**Comment by dxli94** [comment]
@vanpersie32 sorry for the typo. Yes, your understanding is correct that use_dist_eval_sampler is always set to False for retrieval evaluation.
