### ISSUE TITLE
Release BLIP2 stage1 pre-training model

### ISSUE THREAD

**Issue by ustcwhy** [salesforce/LAVIS#272]
Thanks for your wonderful work! I try to use recent advanced LLM (LLaMA) for stage 2 pre-training. 

Do you have any plan to release stage1 pre-training ckpt in the future? Currently, I notice that only [Q-former with ViT-G](https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained.pth) is accessible.

**Comment by LiJunnan1992** [comment]
We have released stage-1 checkpoints with both [ViT-g](https://github.com/salesforce/LAVIS/blob/main/lavis/configs/models/blip2/blip2_pretrain.yaml) and [ViT-L](https://github.com/salesforce/LAVIS/blob/main/lavis/configs/models/blip2/blip2_pretrain_vitL.yaml).
