### ISSUE TITLE
BLIP-2 vs open_clip Vit-G/14 (with LAION-2B) on Imagenet 

### ISSUE THREAD

**Issue by thtang** [salesforce/LAVIS#274]
Is BLIP-2 comparable to open_clip ViT-G/14 (trained with LAION-2B), which claims to have the best released open-source model for 1k ImageNet zero-shot classification so far with an accuracy of 80.1%?

**Comment by LiJunnan1992** [comment]
Hi, BLIP-2 does not pre-train a ViT model. Rather, it uses existing ViT models and LLMs.
