### ISSUE TITLE
Continue pretraining BLIP2

### ISSUE THREAD

**Issue by aburns4** [salesforce/LAVIS#277]
Hi there!

I was hoping to continue pretraining BLIP2 with a custom dataset from the existing pretrained weights, is there functionality that makes this possible? I wasn't sure if it was as simple as modifying `pretrain_stage1.yaml`?

Thank you!

**Comment by LiJunnan1992** [comment]
Yes you could modify `pretrain_stage1.yaml` to use your custom dataset. If you which to continue pre-training from BLIP2 checkpoint, just set `load_pretrained=True `

**Comment by shams2023** [comment]
> 你好呀！
> 
> 我希望继续使用现有预训练权重的自定义数据集来预训练 BLIP2，是否有功能可以实现这一点？我不确定这是否像修改那么简单`pretrain_stage1.yaml`？
> 
> 谢谢你！

I saw the problem you mentioned, which is also the problem I am currently facing. Have you succeeded? If successful, can you share the code?
I am very much looking forward to your reply, as it will be of great help to me!
Thank you!
