### ISSUE TITLE
Maybe a bug? ValueError: Attempting to unscale FP16 gradients.

### ISSUE THREAD

**Issue by Richar-Du** [salesforce/LAVIS#279]
When I set freeze_vit to False, there raises:
```
ValueError: Attempting to unscale FP16 gradients.
```
I find a potential reason here: https://discuss.pytorch.org/t/valueerror-attemting-to-unscale-fp16-gradients/81372

Maybe there is a bug in 
https://github.com/salesforce/LAVIS/blob/8491f1d333cce678b1230cb940fb249253f3ea4d/lavis/models/eva_vit.py#L402
https://github.com/salesforce/LAVIS/blob/8491f1d333cce678b1230cb940fb249253f3ea4d/lavis/models/eva_vit.py#L404
and other `.half()` operation?

**Comment by LiJunnan1992** [comment]
Thanks for raising this issue, when setting freeze_vit to False, you also need to set vit_precision to fp32.

**Comment by Richar-Du** [comment]
Got it. Thanks for your reply:)

**Comment by LiJunnan1992** [comment]
> Got it. Thanks for your reply:) So will .half() then convert fp32 to fp16?

If the ViT precision is set to fp16, then yes.

**Comment by Richar-Du** [comment]
So if I set freeze_vit to False, I must train ViT with fp32. How can I train a ViT with fp16?

**Comment by Richar-Du** [comment]
Got it. Thanks for your patience :)
