### ISSUE TITLE
Finetune CLIP on COCO and Flickr30K

### ISSUE THREAD

**Issue by sdc17** [salesforce/LAVIS#28]
Hello, thanks for your nice work! Are there scripts and configuration files that can be used to finetune CLIP on COCO and Flickr30K, like BLIP ([retrieval_coco_ft.yaml](https://github.com/salesforce/LAVIS/blob/main/lavis/projects/blip/train/retrieval_coco_ft.yaml) and [train_retrieval_coco](https://github.com/salesforce/LAVIS/blob/main/run_scripts/blip/train/train_retrieval_coco.sh))? Thanks again!

**Comment by dxli94** [comment]
Hi @sdc17 , thanks for your interest.

We haven't tried or supported CLIP finetuning on coco or flickr as for now.

PR is welcomed.

Thanks.
