### ISSUE TITLE
How to choose a suitable model and fine-tuning a model that is suitable for a specific field?

### ISSUE THREAD

**Issue by benzzhang** [salesforce/LAVIS#288]
BLIP2 is a wonderful work, and I have benefited al ot from it.

There are many models to choose, such as 'blip2_opt', 'blip2_t5', 'blip_feature_extractor' ...... I want to know what kind of tasks are these models suitable for? **How should I choose the model that suits me?**
Different values of params '**name**' and '**model_type**' in func<**load_model_and_preprocess**> make me confused.

I found a description in "LAVIS/projects/blip2":

- _Use `pretrained_{LLM} `model types for zero-shot image-to-text generation with prompts._

- _Use `caption_coco_{LLM}` model types to generate coco-style captions._

- _Use blip2 model architecture for image-text feature extraction and retrieval._

My task is **generate captions for medical image**. Does it mean that I should choose `caption_coco_{LLM}` model ?

And is there a way for me to fine-tune the model using my own dataset ?

**Comment by benzzhang** [comment]
#281 answer the question about fine-tuning

**Comment by LiJunnan1992** [comment]
You could either use the `pretrained_{LLM}` or `caption_coco_{LLM}` for captioning.

**Comment by shams2023** [comment]
> BLIP2 是一个很棒的作品，我受益匪浅。
> 
> 有很多模型供选择，比如'blip2_opt'、'blip2_t5'、'blip_feature_extractor'……我想知道这些模型适合什么样的任务？我该如何选择适合自己的**模型呢？** func< **load_model_and_preprocess > 中参数“ ****name** ”和“ **model_type** ”的不同值让我感到困惑。************
> 
> 我在“LAVIS/projects/blip2”中找到了描述：
> 
> * _使用`pretrained_{LLM} `模型类型通过提示进行零图像样本到文本生成。_
> * _使用`caption_coco_{LLM}`模型类型生成coco风格的标题。_
> * _使用 blip2 模型架构进行图像数据提取和搜索。_
> 
> 我的任务是**为医学图像生成标题**。这是否意味着我应该选择`caption_coco_{LLM}`型号？
> 
> 有没有办法让我使用自己的数据集配置模型？

I saw the problem you mentioned, which is also the problem I am currently facing. Have you succeeded? If successful, can you share the code?
I am very much looking forward to your reply, as it will be of great help to me!
Thank you!
