### ISSUE TITLE
updating the required torch version

### ISSUE THREAD

**Issue by keunwoochoi** [salesforce/LAVIS#29]
Hi, thanks for the great stuff! 
Is there any plan to update the torch version (from `==1.10` to anything newer), or relax it?

**Comment by dxli94** [comment]
Hi @keunwoochoi ,

Thanks for your interest.

Torch >1.10 is yet fully tested. And as observed by ourselves and other users (https://github.com/salesforce/LAVIS/issues/40), some newest torch version introduces incompatible changes.

For better reproduce our results as reported, you may want to stick with torch 1.10. If you'd like to leverage new torch versions, you may try manual updates

Thanks.

**Comment by dxli94** [comment]
This is now relaxed to torch>=1.10 in https://github.com/salesforce/LAVIS/commit/cd4db98c93d87abe926c9c0e21093f4c56f856de.

However, please be aware the for best reproducing the training for ALBEF and BLIP models, torch=1.10 is recommended.
