### ISSUE TITLE
Details about InstructBLIP's dataset and training

### ISSUE THREAD

**Issue by RayleighChen** [salesforce/LAVIS#292]
Hi, I have three questions about InstructBLIP.

1. There are 28 datasets mentioned in the paper, but there are 26 datasets in Figure 2. What are the other two datasets? 
2. It is mentioned in the paper that BLIP2 does not include Vicuna, so pre-training is required. Is this where the LLM is changed to Vicuna and then the Q-Former is fine-tuned using BLIP2's one-stage training process? Are the settings such as training data and training parameters still the same as the original BLIP2?
3. Will the VL instruction tuning data be released?

Thank you very much for your work. Looking forward to your reply!

**Comment by LiJunnan1992** [comment]
Thanks for your questions.

1. 28 is a typo, we will correct it to 26.
2. Yes we performed the stage2 pre-training in BLIP2 using Vicuna as the LLM.
3. All datasets are public available, which you could download and convert into instruction format for training.
