### ISSUE TITLE
About BLIP-2 Vicuna-7B

### ISSUE THREAD

**Issue by biubiu13** [salesforce/LAVIS#296]
Thank you for your excellent work. I noticed the BLIP2 Vicuna version in InstractBLIP. Can we directly use the Vicuna pre-trained model with BLIP2 now?

**Comment by biubiu13** [comment]
@LiJunnan1992

**Comment by biubiu13** [comment]
@dxli94

**Comment by LiJunnan1992** [comment]
You can follow the instructions in the readme to prepare the vicuna model weights. Thanks.
