### ISSUE TITLE
General question on ITG

### ISSUE THREAD

**Issue by aburns4** [salesforce/LAVIS#303]
Hi there,

I was wondering if you could explain the motivation for having the ITG loss in stage 1 pretraining, and how it differs from the stage 2 pretraining pipeline. If I understand correctly, the only difference is that a large pretrained LLM is used for stage 2 whereas just BERT base is used to decode ITG in stage 1?

Were there ablations you ran to show it was needed in stage 1? I see it's ablated in Table 6 for retrieval, but not other tasks. I understand Figure 5 shows that stage 1 is very useful as a whole, but I am curious about ITG specifically.

Any intuition on this would be greatly appreciated :)

Thank you!

**Comment by LiJunnan1992** [comment]
The ITG loss in stage1 serves a different purpose than the LLM loss in stage2. In stage1, the ITG loss works with ITC and ITM to enforce the queries (in the Qformer) to extract text-relevant image features, achieving vision-language representation learning. Whereas stage2 trains the Qformer to adapt to an LLM.
Thanks.

**Comment by aburns4** [comment]
Makes sense, thank you!

**Comment by ankan8145** [comment]
> The ITG loss in stage1 serves a different purpose than the LLM loss in stage2. In stage1, the ITG loss works with ITC and ITM to enforce the queries (in the Qformer) to extract text-relevant image features, achieving vision-language representation learning. Whereas stage2 trains the Qformer to adapt to an LLM. Thanks.

This is a great work sir !!
I have one question - how queries are updated? Where they are updated can you give the location of that code?
