### ISSUE TITLE
Alternative method for downloading InstructBLIP model parameters when unable to access servers

### ISSUE THREAD

**Issue by pygh0er** [salesforce/LAVIS#312]
Hello！

I'm currently using your **load_model_and_preprocess()** function in my project to download the model parameters of **blip2_vicuna_instruct**. However, it seems that my server is unable to access your servers for the download.

I want to inquire if there are any alternative APIs or links available for downloading the parameters for the instructblip model. I would greatly appreciate it if you could provide me with any alternative methods or resources for obtaining the model parameters.

Thank you very much for your attention and assistance!

**Comment by pygh0er** [comment]
OK, I find the download url in LAVIS/lavis/configs/models/blip2/blip2_instruct_vicuna7b.yaml. It solves my problem.

**Comment by millyshih** [comment]
Did you just download the model from `https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/instruct_blip_vicuna7b_trimmed.pth` (where the url can be find in `LAVIS/lavis/configs/models/blip2/blip2_instruct_vicuna7b.yaml`)?

But how did you input the model to `load_model_and_preprocess()`?

Thanks!

**Comment by macqueen09** [comment]
how to load pth file after download file in LAVIS/lavis/configs/models/blip2/blip2_instruct_vicuna7b.yaml   ?
