### ISSUE TITLE
Where are the pretrained models saved after downloading?

### ISSUE THREAD

**Issue by asrlhhh** [salesforce/LAVIS#32]
Hi, can anyone help me answer where are the all the pretrained model saved in system after the first time downloading it? I am trying to integrate lavis into my docker image and needs sort out the model save path

**Comment by dxli94** [comment]
Hi @asrlhhh , thanks for your interest.

By default weights will be saved to the cache root, as defined in the [default.yaml](https://github.com/salesforce/LAVIS/blob/main/lavis/configs/default.yaml#L8). You can also change this upon your need.

Thanks.

**Comment by asrlhhh** [comment]
Hi I checked the cache_root variable and it by default points to LAVIS/cache in the runtime. However, there isn't such a folder, but I am sure the model is saved somewhere because I didn't see the downloading progress bar

**Comment by dxli94** [comment]
Hi @asrlhhh ,

Sorry for the misleading.

You can find model weights at $TORCH_HOME/hub. This is the same directory the other PyTorch model weights are saved. 

On my local machine, the directory is `~/.cache/torch/hub`.

Can you help confirm this? Thanks.

**Comment by dxli94** [comment]
@asrlhhh Just to follow up, is the issue resolved? Thanks.
