### ISSUE TITLE
BLIP2 results in InstructBLIP paper

### ISSUE THREAD

**Issue by royg27** [salesforce/LAVIS#322]
Hi,

In the zero-shot table (Table 1), Are the BLIP-2 models receive the OCR information, when available? Do they train on the same datasets as in the Instruct BLIP?

Thanks a lot

**Comment by LiJunnan1992** [comment]
BLIP-2 does receive OCR during evaluation when available.

BLIP-2 is not trained on the instruction data used for InstructBLIP.

**Comment by royg27** [comment]
Thank you so much for your reply. 
Just to make sure - BLIP2 was not trained on the instruction dataset, but was it finetuned on the same datasets as in instructBLIP or is it an inference of a the publicly available pretrained model + OCR signal, if applicable?

**Comment by LiJunnan1992** [comment]
In our table, BLIP2 performs inference using its pretrained model + OCR input when available. It is not finetuned.
