### ISSUE TITLE
Custom dataset format

### ISSUE THREAD

**Issue by avinashsai** [salesforce/LAVIS#33]
Hi,

Congrats on the amazing work!! I plan to fine-tune BLIP for image captioning on a custom dataset. What is the input format of the files and changes required in the .yaml files?

**Comment by dxli94** [comment]
Hi @avinashsai ,

Thanks for your interest.

Could you take a look at the adding dataset[ tutoria](https://opensource.salesforce.com/LAVIS//latest/tutorial.datasets.html)l we provided. If there are specific questions, please feel welcomed to ask follow-up questions here.

Thanks.
