### ISSUE TITLE
VQAV2 annotation used in BLIP2

### ISSUE THREAD

**Issue by yanwei-li** [salesforce/LAVIS#338]
Thanks for your amazing work and huge contribution!
I'm wondering what's the difference between ```vqa_val.json``` for training and ```vqa_val_eval.json``` for evaluation (and also ```v2_OpenEnded_mscoco_val2014_questions.json```) that defined in ```lavis/configs/datasets/coco/defaults_vqa.yaml```.
Because most of the questions, answers, and images are identical for training and evaluation.
For example, the first info of ```vqa_val.json``` and ```vqa_val_eval.json``` are both this:
```
{'question_id': 262148000,
 'question': 'Where is he looking?',
 'answer': ['down',
  'down',
  'at table',
  'skateboard',
  'down',
  'table',
  'down',
  'down',
  'down',
  'down'],
 'image': 'val2014/COCO_val2014_000000262148.jpg',
 'dataset': 'vqa'}
```

**Comment by LiJunnan1992** [comment]
Hi, thanks for your question. 

When finetuning on VQAv2, we evaluate on the test-dev and test-std set. The Table4 column title in BLIP-2 paper should be modified and we will update the paper. Meanwhile please refer to our BLIP paper (https://arxiv.org/pdf/2201.12086.pdf, Table 8) for the correct column title.

**Comment by yanwei-li** [comment]
Thanks for your reply! It really helps.
