### ISSUE TITLE
Relation between ITE and GradCAM

### ISSUE THREAD

**Issue by weibifan** [salesforce/LAVIS#35]
在3.1节，第2自然段说是ITE完成图像与问题的相似度计算，第3自然段又说GradCAM完成相似度计算，这两个模块是啥关系？
怎么理解这句话?To identify relevant image patches, we feed the image v and the question t to the ITE network and apply a variation of GradCAM....  应用GradCAM在干什么？

English translations by @dxli94 :
"In Section, para. 2, you mention ITE measures the similarities between images and questions, in para.3 you mention use GradCam to measure similarity." What is the relation between ITE and GradCAM?

Second, how to understand "To identify relevant image patches, we feed the image v and the question t to the ITE network and apply a variation of GradCAM"? What is GradCAM doing here?"

**Comment by anthonytmh** [comment]
Hi @weibifan ,

Thanks for your interest. 

@dxli94 has explained it well. Essentially, from the ITE network, we obtain the gradient and cross-attention map. Then, we use them to compute the GradCAM, here, we use cross-attention map as the class-activation map (CAM).  

Thanks.

**Comment by weibifan** [comment]
Thanks for your carefull explanation！
