### ISSUE TITLE
Why not having LLaVA or miniGPT4?

### ISSUE THREAD

**Issue by yhyu13** [salesforce/LAVIS#351]
Maybe a stupid question, I am not sure why LLaVA or miniGPT4 is not listed as part of the solution provided here. Due to Lience or something?

**Comment by LiJunnan1992** [comment]
InstructBLIP shows better performance compared to LLaVA and miniGPT4 in our experiments.

**Comment by yhyu13** [comment]
@LiJunnan1992 You must be refering to this paper https://arxiv.org/pdf/2305.06500.pdf

and this section

![image](https://github.com/salesforce/LAVIS/assets/19365678/c1fef3f3-5981-4f7e-8148-40a6a06d3b37)


Thanks for pointing this out!
