### ISSUE TITLE
BLIP-2 Multiple Choice VQA

### ISSUE THREAD

**Issue by sgvaze** [salesforce/LAVIS#355]
Hi, thanks for the great work!

This may be a basic question, but how do you evaluate in the multiple choice VQA setting? And how do the various models perform in open-ended generation vs multiple-choice?

When I try prompting as you would a language model (e.g for MMLU), the answers don't seem to make much sense. E.g if I try a prompt like this I cannot get sensible results:
"{image}
Question: How many dogs are in the image?
(A) 1
(B) 2
Answer:"

This seems important for questions where there might not be short/one-word answers, and evaluating without multiple choice is difficult.

**Comment by LiJunnan1992** [comment]
For multi-choice VQA evaluation, you can use ranking with the LLM's log-probability.

**Comment by sgvaze** [comment]
Sorry for the late reply - thanks for the help! Closed.
