### ISSUE TITLE
Multi-round conversation (InstructBLIP)

### ISSUE THREAD

**Issue by huangjy-pku** [salesforce/LAVIS#357]
In multi-round conversation scenario, how does the `InstructBLIP` model encode the context in previous conversation rounds? Simply concatenating the previous-round conversations? My concern is the `max_txt_len=128` may be easily exceeded. So how do you make the multi-round conversation demos (obviously longer than 128)?

BTW, what is the `text_input` made of in [https://github.com/salesforce/LAVIS/tree/59273f651b9bffb193d1b12a235e909e9f826dda/projects/instructblip#instruction-tuning](https://github.com/salesforce/LAVIS/tree/59273f651b9bffb193d1b12a235e909e9f826dda/projects/instructblip#instruction-tuning)? Again, if it contains all the instructions and responses of previous rounds, the `max_txt_len` may be easily exceeded?

**Comment by LiJunnan1992** [comment]
We simply concatenate the previous-round conversations. You may extend the maximum length of the LLM to encode more context information. For the Q-former's `text_input`, it is expected to contain the most informative context, which may or may not be the same as the text input to LLM.
Thanks.

**Comment by huangjy-pku** [comment]
Seems there is no difference between the `text_input` for `LLM` and the `text_input` for `Q-former`. They both tokenized `samples['text_input']` or `prompt`. What do you mean by the difference here?

**Comment by LiJunnan1992** [comment]
In our implementation, the text input to the LLM and Q-former is the same. However, you could also give different input. The text input to the Q-former serves as a condition for visual feature extraction. Please refer to our paper for details. Thanks.

**Comment by MrWaterZhou** [comment]
> In our implementation, the text input to the LLM and Q-former is the same. However, you could also give different input. The text input to the Q-former serves as a condition for visual feature extraction. Please refer to our paper for details. Thanks.

Hi, I would like to know if it would be helpful to include 'background' as an instruction word when working on the image caption task, as I want to describe the background of the image.
