### ISSUE TITLE
LLAVA miniGPT4 and InstructBLIP

### ISSUE THREAD

**Issue by zhangqingwu** [salesforce/LAVIS#358]
Thanks for the great work!
The following is the feeling of using these models：
Comparing LLAVA miniGPT4 and InstructBLIP, it is found that the results generated by llava and minigpt4 under multiple rounds of dialogue may be more in line with expectations, such as trying some scoring tasks. The ability of InstructBLIP seems to be the ability to describe details. But for some question-and-answer tasks, the effect seems to be biased.
Does the author have such experience, or is there a solution? Is it necessary to finetune with dialogue data?

**Comment by LiJunnan1992** [comment]
Hi, please refer to #357  for tasks with long context.
