### ISSUE TITLE
Failed to download msrvtt

### ISSUE THREAD

**Issue by wei10cool** [salesforce/LAVIS#36]
```
from lavis.datasets.builders import load_dataset
msrvtt_dataset = load_dataset("msrvtt_caption")
```
as picture
![image](https://user-images.githubusercontent.com/11017886/199537063-10263d81-82f2-41d8-b1fe-41dbda51bb1b.png)

another way still failed
```LAVIS\lavis\datasets\download_scripts>python download_msrvtt.py
Downloading https://download1602.mediafire.com/jslug277m67g/x3rrbe4hwp04e6w/train_val_videos.zip to train
Failed to download or extracting datasets. Aborting.
Merging to C:\Users\jianwei\anaconda3\envs\thesis\lib\site-packages\lavis\..\cache\msrvtt\videos
Failed to merging datasets. Aborting.```

**Comment by dxli94** [comment]
Hi @wei10cool ,

Thanks for your interest and well-spotting.

MSRVTT download links expire every a few moments. You may download manually from https://www.mediafire.com/folder/h14iarbs62e7p/shared or update the downloading scripts with the new URLs.

We'll update the download scripts to reflect this.

Thanks.

**Comment by dxli94** [comment]
Have now updated the URLs with the newest.

These URLs are dynamic - they change over time. Therefore, I also included instructions for further downloads.

Closed for now.
