### ISSUE TITLE
samples["text_output"] for COCO fine-tuning key error

### ISSUE THREAD

**Issue by aburns4** [salesforce/LAVIS#364]
Hi,

I've seen the existing issues (issue #139) regarding the `text_output` key for prefix LM pretraining. However, this error also comes up during fine-tuning with COCO as well when run with the blipt5 flanxl model. Some questions:

1. Do you use the same splitting strategy as discussed in issue #139 when finetuning? Or is just the prompt "a photo of" supposed to be the `text_input`?
2. Where is the prompt "a photo of" piped into the LLM inputs?

Thank you!

**Comment by LiJunnan1992** [comment]
Thanks for your question.

1. For finetuning BLIP2-T5 on image caption, "a photo of" is the `text_input` and the caption is the `text_output`
2. `text_input` will be concatenated with the Q-Former's output as the input embedding to the LLM: https://github.com/salesforce/LAVIS/blob/59273f651b9bffb193d1b12a235e909e9f826dda/lavis/models/blip2_models/blip2_t5.py#L145

**Comment by aburns4** [comment]
Thank you!

**Comment by ldfandian** [comment]
> Thanks for your question.
> 
> 1. For finetuning BLIP2-T5 on image caption, "a photo of" is the `text_input` and the caption is the `text_output`
> 2. `text_input` will be concatenated with the Q-Former's output as the input embedding to the LLM: https://github.com/salesforce/LAVIS/blob/59273f651b9bffb193d1b12a235e909e9f826dda/lavis/models/blip2_models/blip2_t5.py#L145

From the code, it looks like '' (empty prompt) is used in the pretrain config file "lavis/configs/models/blip2/blip2_pretrain_flant5xl.yaml" but 'a photo of' prompt is used in the coco fine-tune config file "lavis/configs/models/blip2/blip2_caption_flant5xl.yaml".

Can you please tell why fine-tune is different from pretrain?

**Comment by dxli94** [comment]
@ldfandian "a photo of" often appears in the pretraining data, not on COCO. Adding it as a prompt during fine-tuning reduces the gap between pretrain and finetuning.

**Comment by ldfandian** [comment]
> @ldfandian "a photo of" often appears in the pretraining data, not on COCO. Adding it as a prompt during fine-tuning reduces the gap between pretrain and finetuning.

I was confused because blip2_pretrain_flant5xl.yaml has an empty prompt. Should I added it by myself for training ?
