### ISSUE TITLE
Great work! However i would like to know use cases about how BLIP-Diffusion can be used in Salesforce and how will it make job easier for us users?

### ISSUE THREAD

**Issue by Akashdeep122** [salesforce/LAVIS#366]

**Comment by dxli94** [comment]
BLIP-Diffusion facilitates effective subject-driven image generation and editing. It is an integral part of the Generative AI initiative.

**Comment by Akashdeep122** [comment]
Okay Thanks , So I also wanted to know what is The meaning/full form of BLIP in BLIP-Diffusion? As BLIP is all in capital it may stand for an acronym.

**Comment by ChristiaensBert** [comment]
@Akashdeep122 This BLIP-Diffusion model is based on the BLIP (bootstrapping Language Image Pre-training) model that has been developed by SalesForce. They are using a variant to make the BLIP-Diffusion architecture

**Comment by Akashdeep122** [comment]
Thank you for letting me know :)
