### ISSUE TITLE
Release of the BLIP-2 pre-instruct tuned Vicuna-{7b/13b} models

### ISSUE THREAD

**Issue by lavoiems** [salesforce/LAVIS#369]
Is the BLIP-2 model trained with Vicuna-7b and Vicuna-13 available for us to use? Otherwise, is it possible to release the parameters of these models?

Thank you for your contribution to open science!

**Comment by LiJunnan1992** [comment]
Hi, please refer to https://github.com/salesforce/LAVIS/issues/344 for pre-instruct Vicuna7b model
