### ISSUE TITLE
[InstructBLIP] Unable to reproduce paper results for VSR and HatefulMemes

### ISSUE THREAD

**Issue by utsavgarg** [salesforce/LAVIS#370]
Hi, 

I am having trouble reproducing the results for the VSR and HatefulMemes datasets reported in the paper. I am using a simple prompt to check if the picture aligns with the caption for VSR and if there's anything hateful in the image for HatefulMemes. For prediction, I use the `predict_class` method with four choices `['yes', 'true', 'no', 'false']`. It would be great if you could share the inputs used for these two datasets. Thanks!

**Comment by LiJunnan1992** [comment]
You can find our evaluation prompt in Appendix E our of paper, thanks.
https://arxiv.org/pdf/2305.06500.pdf
