### ISSUE TITLE
Defining text input and output for custom caption and VQA datasets

### ISSUE THREAD

**Issue by aburns4** [salesforce/LAVIS#373]
Hi,

I'm continuing to find the `text_input` and `text_output` definitions a bit confusing since they are used differently for different tasks and different models.

I have custom caption and vqa datasets for which I'd like to make sure I am defining samples correctly. For captioning, I just want the prompt to be the `text_input`, not splitting the target caption during fine tuning. So, I've been passing in an empty string for this field with FlanT5 and the full caption for `text_output`. However, only `text_input` is used with OPT, for both the inputs and target outputs? Can you explain this? How should I be assigning the target caption in this case?

Then, for VQA the `text_input` should always be the question and the `text_output` the answer. But again, OPT only has the `text_input` field in its data samples + that is all that's used in the forward function.

Could you please describe what should be done in these cases? I could totally be missing the relationship between the fields, the prompt, preprocessing, and masking, but an explanation would be greatly appreciated.

Thanks!

**Comment by LiJunnan1992** [comment]
Thanks for your question.

Your understanding for image captioning is correct. For OPT, `text_input` is the caption. For FlanT5, `text_output` is the caption. For both models, you may optionally add a prompt "a photo of" to the `text_input`. For OPT, loss should not be applied on the prompt: https://github.com/salesforce/LAVIS/blob/59273f651b9bffb193d1b12a235e909e9f826dda/lavis/models/blip2_models/blip2_opt.py#L141.

For VQA with OPT, the `text_input` contains the question+answer sequence. However, the loss on the question (i.e. prompt) should also be masked.

**Comment by rese1f** [comment]
how about Vicuna, is `text_input` the caption? Many thanks @LiJunnan1992

**Comment by LiJunnan1992** [comment]
Yes for decoder LLMs, all texts will be passed as `text_input`. You just need to masked out the loss on the prompt.

**Comment by rese1f** [comment]
> Yes for decoder LLMs, all texts will be passed as `text_input`. You just need to masked out the loss on the prompt.

Thanks!

**Comment by ldfandian** [comment]
> Yes for decoder LLMs, all texts will be passed as `text_input`. You just need to masked out the loss on the prompt.

How about the instructBlip model?

If I understant it correct, in the instructBlip model, text_input is the prompt and text_output is the caption, right?

**Comment by LiJunnan1992** [comment]
> > Yes for decoder LLMs, all texts will be passed as `text_input`. You just need to masked out the loss on the prompt.
> 
> How about the instructBlip model?
> 
> If I understant it correct, in the instructBlip model, text_input is the prompt and text_output is the caption, right? @LiJunnan1992

Yes
