### ISSUE TITLE
blip diffusion

### ISSUE THREAD

**Issue by chenluuyou** [salesforce/LAVIS#380]
I can't find the code under the address of the original blip diffusion
[https://github.com/salesforce/LAVIS/tree/main/projects/blip-diffusion](https://github.com/salesforce/LAVIS/tree/main/projects/blip-diffusion)

**Comment by JPlin** [comment]
+1

**Comment by WilTay1** [comment]
+1

**Comment by hpstyl** [comment]
+1

**Comment by xywen97** [comment]
+1

**Comment by JonnyS1226** [comment]
+1 also the same question

**Comment by dxli94** [comment]
Hi @chenluuyou, @JonnyS1226, @WilTay1, @JPlin, @hpstyl, @xywen97, thanks for the interest and patience. Please keep an eye on https://github.com/salesforce/LAVIS/pull/417.
