### ISSUE TITLE
[BLIP2] The attention mask for visual tokens in causal LM

### ISSUE THREAD

**Issue by liyz15** [salesforce/LAVIS#393]
It seems we are passing attention masks of shape [batch, seq_len] for visual queries even in causal LM such as [opt](https://github.com/salesforce/LAVIS/blob/4a85b17846ee62f09c40f37cc955dd33c2abec68/lavis/models/blip2_models/blip2_opt.py#L124)/[vicuna](https://github.com/salesforce/LAVIS/blob/4a85b17846ee62f09c40f37cc955dd33c2abec68/lavis/models/blip2_models/blip2_vicuna_instruct.py#L181C15-L181C15).

This is fine for T5 model because T5 has a bi-directional encoder. But casual LM will create casual mask automatically unless explicitly passing in attention mask of shape [batch, seq_len, seq_len]. It will be more sensible for all visual queries to see each other, which also aligns with the paper.

**Comment by Andy1621** [comment]
Great

**Comment by LiJunnan1992** [comment]
We have experimented bi-directional attention on the visual embeddings into the causal LM, but found no improvement. 
Thanks.

**Comment by liyz15** [comment]
> 

Thank you for your response
