### ISSUE TITLE
Pretrained on 224x224 and finetuned on 364x364 in BLIP2 retrieval finetuning?

### ISSUE THREAD

**Issue by inkzk** [salesforce/LAVIS#400]
Seems like there is resolution difference between pretraining and finetuning. And what's the reason for that?
Thank U!

**Comment by ldfandian** [comment]
I guess the model trainer is going to resize the input to 224 nevertheless.

**Comment by inkzk** [comment]
> I guess the model trainer is going to resize the input to 224 nevertheless.
> 
> You can take a look at the **init** implementation of Blip2OPT class.

seems not like that

**Comment by ldfandian** [comment]
> > I guess the model trainer is going to resize the input to 224 nevertheless.
> > You can take a look at the **init** implementation of Blip2OPT class.
> 
> seems not like that

here?

![image](https://github.com/salesforce/LAVIS/assets/5018331/0e7ea137-a684-4cbf-81ff-3799f9403f43)

![image](https://github.com/salesforce/LAVIS/assets/5018331/8190fa1b-02aa-4523-9afc-cd111ebc0295)

**Comment by inkzk** [comment]
> > > I guess the model trainer is going to resize the input to 224 nevertheless.
> > > You can take a look at the **init** implementation of Blip2OPT class.
> > 
> > 
> > seems not like that
> 
> here?
> 
> ![image](https://user-images.githubusercontent.com/5018331/251359109-0e7ea137-a684-4cbf-81ff-3799f9403f43.png)
> 
> ![image](https://user-images.githubusercontent.com/5018331/251359354-8190fa1b-02aa-4523-9afc-cd111ebc0295.png)

`img_size` was set to 364 in yaml, 224 is just a default value..

**Comment by ldfandian** [comment]
You are right. My misunderstanding. Sorry.

**Comment by LiJunnan1992** [comment]
Increasing the image resolution leads to improved performance on downstream tasks.

**Comment by inkzk** [comment]
> Increasing the image resolution leads to improved performance on downstream tasks.

@LiJunnan1992 
Thanks for the reply. And I want to know that, whether the vit initialized with the same weight between `224x224 pretrain` and `364x364 finetune`? Seems like it's two different vit between pretrain and finetune

**Comment by LiJunnan1992** [comment]
The finetuned 364 ViT is initialized from the pre-trained frozen 224 ViT. The position encodings are interpolated.
