### ISSUE TITLE
[BLIP2] Missing Causal Mask

### ISSUE THREAD

**Issue by Yui010206** [salesforce/LAVIS#402]
Hi, I find it seems q-former pretraining does not use causal [masks](https://github.com/salesforce/LAVIS/blob/main/lavis/models/blip2_models/blip2_qformer.py#L259) for image caption as mentioned in the paper.  Is there anything I missed? Thanks!

**Comment by LiJunnan1992** [comment]
The causal mask is implemented [here](https://github.com/salesforce/LAVIS/blob/93e0179e0fe94299b3d595fefc99bdd980733411/lavis/models/blip2_models/Qformer.py#L770)
