### ISSUE TITLE
have you tried resnet (like resnet-50) network as the image encoder here?

### ISSUE THREAD

**Issue by ldfandian** [salesforce/LAVIS#405]

**Comment by LiJunnan1992** [comment]
Yes, ViTs are much better than ResNets.

**Comment by ldfandian** [comment]
> Yes, ViTs are much better than ResNets.

Can you share some result report data please?

**Comment by LiJunnan1992** [comment]
The conclusion was drawn based on preliminary experiments.

**Comment by ldfandian** [comment]
> The conclusion was drawn based on preliminary experiments.

just curious, how much is the gap between resnet and vit image encoder? 10%, 20%?
