### ISSUE TITLE
Visual Genome dataset caption preprocessing 

### ISSUE THREAD

**Issue by happywu** [salesforce/LAVIS#41]
Hi, 

I notice that the VG caption annotation provided and used in papers has around 800k captions, however the original VG annotation has 5.4M regional captions, wondering what kind of pre-processing is involved to reach the current provided VG caption annotations?

Best

**Comment by dxli94** [comment]
Hi @happywu ,

Thanks for your interest. You can find related discussion here (https://github.com/salesforce/ALBEF/issues/2).

Best

**Comment by happywu** [comment]
Thanks!
