### ISSUE TITLE
pip install salesforce-lavis 安装不上问题怎么解决

### ISSUE THREAD

**Issue by chenglong199206** [salesforce/LAVIS#419]
pip install salesforce-lavis 这部分的时候安不上了，感觉是nvidia版本或者配置的问题，内存空间足够大，请帮忙看看，谢谢
![image](https://github.com/salesforce/LAVIS/assets/139129958/f33e1b9e-e6b4-4ffe-9861-113959c60610)

**Comment by dxli94** [comment]
As the error message indicates, you are running out of the disk space.

My guess is you might be examining a wrong disk partition / path. Please double-check the disk space of where your environment is installed.

**Comment by chenglong199206** [comment]
磁盘空间是足够的，还有好几个T那，之前按照其他包也遇到过磁盘空间的问题，实际上并不是这个问题导致的
