### ISSUE TITLE
Error in load_model_and_preprocess

### ISSUE THREAD

**Issue by pqviet** [salesforce/LAVIS#42]
Hi, I met an error when loading the model pnp_vqa
model, vis_processors, txt_processors = load_model_and_preprocess(name="pnp_vqa", model_type="base", is_eval=True, device=device)
...
File ~/anaconda3/envs/lavis/lib/python3.8/site-packages/torch/serialization.py:600, in load(f, map_location, pickle_module, **pickle_load_args)
    595 if _is_zipfile(opened_file):
    596     # The zipfile reader is going to advance the current file position.
    597     # If we want to actually tail call to torch.jit.load, we need to
    598     # reset back to the original position.
    599     orig_position = opened_file.tell()
--> 600     with _open_zipfile_reader(opened_file) as opened_zipfile:
    601         if _is_torchscript_zip(opened_zipfile):
    602             warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
    603                           " dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to"
    604                           " silence this warning)", UserWarning)

File ~/anaconda3/envs/lavis/lib/python3.8/site-packages/torch/serialization.py:242, in _open_zipfile_reader.__init__(self, name_or_buffer)
    241 def __init__(self, name_or_buffer) -> None:
--> 242     super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
---------------------------------------------------------------------------------------------
I think this issue happens when the file is not downloaded completely.
Is there any way to redownload the model?

**Comment by pqviet** [comment]
I just removed the downloaded files from the cache and redownloaded them. It fixed the problem. Thanks.

**Comment by macqueen09** [comment]
same question , how to use offline pth file and Where is the  cache should be remove ? thanks very much .
