### ISSUE TITLE
Assigning non-default DATASET_CONFIG_DICT

### ISSUE THREAD

**Issue by aburns4** [salesforce/LAVIS#421]
Hi,

I see you can have multiple dataset configs to choose from by creating additional key-value pairs to DATASET_CONFIG_DICT in the appropriate builder. However, I am not sure how to actually assign which config should be used? Can you please explain how to assign it to a non-default value? It looks to me like the type is always set to default in the class method `default_config_path`.

Thank you!

**Comment by dxli94** [comment]
You can specify the dataset type in config yamls like this: https://github.com/salesforce/LAVIS/blob/main/lavis/projects/blip2/eval/gqa_zeroshot_flant5xl_eval.yaml#L14.

The particular code you may want to look at is: https://github.com/salesforce/LAVIS/blob/main/lavis/common/config.py#L100.

**Comment by aburns4** [comment]
Thank you very much!
