### ISSUE TITLE
Questions about VQAv2 split

### ISSUE THREAD

**Issue by stdKonjac** [salesforce/LAVIS#423]
Thanks for your excellent work！
I am a little confused about how to reproduce the reported val and test-dev results on VQAv2. 
In your provided evaluation scripts, e.g., validate_vqa_zeroshot_opt.sh, there is only one eval protocol, i.e., eval_vqa, that contains a val_vqa_eval.json. Is this correspond to the val results or test-dev result? 
If it belongs to one of them, how can I reproduce another result? @LiJunnan1992

**Comment by dxli94** [comment]
Hi @stdKonjac,

Just change the test split to "test": https://github.com/salesforce/LAVIS/blob/main/lavis/projects/blip2/eval/vqav2_zeroshot_opt_eval.yaml#L45.

The ground-truth of VQAv2 test split is not disclosed. You need to upload the result to evaluation server to get the score.

**Comment by stdKonjac** [comment]
> Hi @stdKonjac,
> 
> Just change the test split to "test": https://github.com/salesforce/LAVIS/blob/main/lavis/projects/blip2/eval/vqav2_zeroshot_opt_eval.yaml#L45.
> 
> The ground-truth of VQAv2 test split is not disclosed. You need to upload the result to evaluation server to get the score.
Thanks for your quick response😄, it helps a lot!
