### ISSUE TITLE
Convergence and force output

### ISSUE THREAD

**Issue by mcjinye** [salesforce/LAVIS#43]
Hi,

I am following the example in https://opensource.salesforce.com/LAVIS//latest/tutorial.training-example.html and using my own dataset for a retrain. Perhaps my data are not enough so it keeps running for 100+ epochs. Is there a way to tune the tolerance for the convergence? Or is there a way to force output the model if the retrain reaches max_epoch? Thanks!

**Comment by dxli94** [comment]
Hi @mcjinye, thanks for your interest.

You can change max_epoch to limit the number of epochs, see https://github.com/salesforce/LAVIS/blob/main/lavis/projects/blip/train/caption_coco_ft.yaml#L34.

We don't track the convergence of the model.

You may force saving the last model after the max_epochs by adding `https://github.com/salesforce/LAVIS/blob/main/lavis/runners/runner_base.py#L381` to https://github.com/salesforce/LAVIS/blob/main/lavis/runners/runner_base.py#L387.

Thanks.

**Comment by mcjinye** [comment]
Hi @dxli94, thank you for the quick response! I think I misunderstand the tools. Correct me if I am wrong. I believe this link https://opensource.salesforce.com/LAVIS//latest/tutorial.training-example.html# is to provide test score based on the current pretrained/finetuned model right? If I want to output the model configuration for further usage, like those examples in the repo, I should follow https://opensource.salesforce.com/LAVIS//latest/tutorial.models.html to pretrain/finetune and output model. Is this correct?

I have a follow-up question on this topic. I want to do a zero-shot classification with my own dataset. If I don't want to use the existing model, should I pretrain the base model (blip_pretrain) or tune this blip_feature_extractor? I notice that in the example you are using blip_feature_extractor. But when I retrain it, it seems like the repo is not supporting retraining blip_feature_extractor. (Although I feel like the final layer of blip_pretrain is what we have from blip_feature_extractor).

Sorry for a lot of questions. This is a great work. Thanks!
