### ISSUE TITLE
About the accum_grad_iters

### ISSUE THREAD

**Issue by Pefect96** [salesforce/LAVIS#438]
I want to ask if we could address the problem of "cuda out of memory" by seting the accum_grad_iters > 1. 
For example, if we set accum_grad_iters = 8, and batch_size_train = 32, then, the batch size in training is 256?

Looking forward to your reply.

**Comment by dxli94** [comment]
Yes. That's feasible.

**Comment by rafa-cxg** [comment]
> Yes. That's feasible.

But why do you accumulate losses without average them? Considering that the normal loss catculation is `size_average = True`.
