### ISSUE TITLE
[blip2 train bug] about Dongxu 2023/7/21 submit

### ISSUE THREAD

**Issue by xingenju** [salesforce/LAVIS#449]
code runner_base.py: Line 366.
![image](https://github.com/salesforce/LAVIS/assets/5735488/e0d5c052-8a9d-4797-8519-708007f0a498)

The datasets has not been merged here, should call dataloaders() before, or merge datasets before
image

**Comment by dxli94** [comment]
Thanks for raising the issue. This happened due to an incorrect branch merging.

I've made a hotfix in https://github.com/salesforce/LAVIS/commit/c578ed1a18f223b4ac55ecadb502049c3cbefade that disables before_training() if using epoch-based runner as for now.

Kindly check it out.
