### ISSUE TITLE
How to implement Subject-driven Editing via Cross-attention Control in blip-diffusion

### ISSUE THREAD

**Issue by fantyan** [salesforce/LAVIS#458]
I'm interested in implementing Subject-driven Editing in blip-diffusion via Cross-attention Control.

How can I then use the cross-attention maps to guide the model to selectively edit certain regions of the image?
Any tips or code snippets to point me in the right direction would be greatly appreciated. 

Thanks!

**Comment by dxli94** [comment]
@fantyan I will update relevant code and examples this week.

**Comment by dxli94** [comment]
See f982acc.

Thanks.
