### ISSUE TITLE
pretrain with blip2 stage1

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [salesforce/LAVIS#470]
1,How to pretrain blip2 stage 1 with multi node multi gpus?
2,dataset sample ratio with multi datasets?
Looking forward to your reply

**Comment by aburns4** [comment]
Same issue. Anyone else figure this out?

**Comment by yongxinwang-ai** [comment]
@ZhaoyangLi-nju hi guy, did u solve the problem?

**Comment by vanpersie32** [comment]
@aburns4 same issue. Have you solved the problem

**Comment by vanpersie32** [comment]
@ZhaoyangLi-nju  Have you solved the problem
