### ISSUE TITLE
Clarifying InstructBLIP training stages

### ISSUE THREAD

**Issue by spetryk** [salesforce/LAVIS#471]
Thanks for your continued development & for open-sourcing InstructBLIP weights!

From reading the BLIP2 and InstructBLIP papers, this is how I understand the high-level pipeline of training InstructBLIP - could you please clarify if I am misunderstanding something?

1. [BLIP2] Stage 1 - vision-language representation learning (no LLM, just doing ITM/ITG/ITC).
2. [BLIP2] Stage 2 - add LLM (e.g., Vicuna), do next word prediction.
3. [InstructBLIP] Initialize InstructBLIP with weights from step (2).
4. [InstructBLIP] Convert all data into instruction format.
5. [InstructBLIP] Stage 1 (with instruction prompts).
6. [InstructBLIP] Stage 2 (with instruction prompts).

Edit: Additionally, what step does the Training and Hyper-parameters paragraph in the InstructBLIP paper (Section 2.6) refer to?

**Comment by dxli94** [comment]
@spetryk no additional vision-language representation learning for instructBLIP is needed. Namely, step 5 is not needed.
