### ISSUE TITLE
PNP-VQA on UnifiedQAv2 11b

### ISSUE THREAD

**Issue by Richar-Du** [salesforce/LAVIS#48]
Thanks for your work in Plug-and-Play VQA: Zero-shot VQA by Conjoining Large Pretrained Models with Zero Training! I notice a config for a model with 3b parameters, but 11b is unavailable. What should I do to test UnifiedQAv2 with 11b parameters? 

Thanks in advance, I'm looking forward to your reply :)

**Comment by dxli94** [comment]
Hi @Richar-Du, thanks for your interest.

The 11b model requires model can't fit in a 40Gb GPU. It requires model parallelism, which LAVIS does not support natively at this stage.

Our colleague @anthonytmh will provide a notebook with 11b model in the coming days. Please stay subscribed to the issue for updates.

Thanks.

**Comment by Richar-Du** [comment]
Thanks for your reply. Would you mind providing a version loading model with CPU first, so that I can have a quick test on my task?

**Comment by anthonytmh** [comment]
Hi @Richar-Du, for 11b model, the only difference is the question answering model - UnifiedQAv2 (11B) from allenai (available from huggingface). So, for cpu version, you need to modify the config file: 
https://github.com/salesforce/LAVIS/blob/1bb0ba7fad3ef40d874d028e2587dafbc1a5fd60/lavis/configs/models/pnp-vqa/pnp_vqa_3b.yaml#L49-L51

`pretrained: "allenai/unifiedqa-v2-t5-11b-1363200"`;
`t5_config_path: "configs/models/pnp-vqa/unifiedqav2_11b_config.json"` 


To obtain `unifiedqav2_11b_config.json`: 
```
from transformers import T5ForConditionalGeneration
model = T5ForConditionalGeneration.from_pretrained("allenai/unifiedqa-v2-t5-11b-1363200")
model.config.to_json_file("configs/models/pnp-vqa/unifiedqav2_11b_config.json")
```

Thanks.

**Comment by Richar-Du** [comment]
Got it, thanks!
