### ISSUE TITLE
Seems inconsistency between figure in ALBEF paper and corresponding code

### ISSUE THREAD

**Issue by teamwong111** [salesforce/LAVIS#480]
The figure 1: Illustration of ALBEF in the paper looks like this

<img width="774" alt="image" src="https://github.com/salesforce/LAVIS/assets/47851024/3ffad820-5883-4497-a6ef-fdb5895181ba">

The MLM part contains a 6 layers text encoder and a 6 layers multimodal encoder.

But the corresponding code at `albef_pretrian.py` line 305 seems a 12 layers multimodal encoder.

I'm not sure if I got something wrong.

Hope for your reply.

**Comment by dxli94** [comment]
@teamwong111 We have a customized config file for BERT text encoder, which defines the number of layers for multimodal encoder. Check this out: https://github.com/salesforce/LAVIS/blob/main/lavis/configs/models/med_config_albef.json#L21.

**Comment by teamwong111** [comment]
Sorry for the late reply

You may have misunderstood me. What I mean is that from the code it seems that text embeddings interact with image embeddings at each transformer layer to get the output of MLM, which is inconsistent with the figure in ALBEF paper.

You can see in the `albef_pretrain.py` file lines 304 - 313

```
mlm_output = self.text_encoder(
     input_ids,
     attention_mask=text.attention_mask,
     encoder_hidden_states=image_embeds,
     encoder_attention_mask=image_atts,
     return_dict=True,
     labels=labels,
     soft_labels=F.softmax(logits_m, dim=-1),
     alpha=alpha,
)
```

Here original text inputs(`input_ids`) and `image_embeds` are input to `text_encoder`, which will cause each transformer layer the text passes through to interact with the image embeddings.

The code related to `text_encoder` should be in `med.py`. The `forward` function of class `BertEncoder` has a parameter `mode`, and its default value is `"multimodal"`. When the default value is used, each layer of `BertEncoder` will interact between modalities.
