### ISSUE TITLE
Qusetion about paper: "BLIP-Diffusion

### ISSUE THREAD

**Issue by Gynjn** [salesforce/LAVIS#482]
First of all, thanks for your effort about this paper.

BTW, I'm confused the meaning of the paper in some phrase.

"Empirically, we find that the originally implemented 32 output features often overpower the CLIP text embeddings when used in combination for image generation. Therefore, we instead half the number of query tokens and output 16 features." (Page 4)

It said with 32 features, it overpower the clip perfomance. Why did you half the number of features. Is it for computation efficiency?

**Comment by dxli94** [comment]
@Gynjn thanks for your interest. The subject embeddings are concatenated with CLIP embedding as condition. Having more subject embeddings compete with CLIP text embeddings. Thus, we reduce the number of subject embeddings to 16.

**Comment by Gynjn** [comment]
Got it, Thanks!
