### ISSUE TITLE
How to apply multimodal feature for multimodal classification?

### ISSUE THREAD

**Issue by behroozazarkhalili** [salesforce/LAVIS#49]
Hi everyone,
First of all, thank you so much for this great package.

I would be so grateful if you could kindly provide me with an example code of how the multimodal feature can be used for multimodal classification, as you mentioned [here](https://github.com/salesforce/LAVIS#unified-feature-extraction-interface).

Best,

**Comment by dxli94** [comment]
Hi, thanks for your interest.

You can take multimodal embedding to send them to a classifier, which can be as simple as an MLP.

This can be useful when you want to classify captioned images. One example is the visual entailment (VE) task, which is a three-way classification. You may want to take a look at the ALBEF VE model for reference.

Thanks.
