### ISSUE TITLE
what is your success rate when downloading laion115m?

### ISSUE THREAD

**Issue by yxchng** [salesforce/LAVIS#498]
i am trying to reproduce blip 2 using laion_synthetic_filtered_large but it seems like many urls are no longer working. can i know what is your success rate when downloading the dataset?

**Comment by dxli94** [comment]
Hi @yxchng, we use the tool img2dataset to download the data. The success rate was 60-70%.

You may choose to download a larger portion of LAION-EN-2B so as to get a comparable scale of pre-training data.
