### ISSUE TITLE
Additional requirements for COCO caption finetuning

### ISSUE THREAD

**Issue by moskomule** [salesforce/LAVIS#5]
Hi, thank you for sharing a great library.

I want to fine-tune the model on COCO caption, which uses `pycocoevalcap` that depends on `stanford-corenlp`.

While running `run_scripts/blip/train/train_caption_cocosh`, it causes an error when the `SPICE` score is calculated, because of `Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module`.

I guess this error is due to its dependency on a specific version of Java. Which version of Java do you use in the development?

Thank you!

**Comment by moskomule** [comment]
You need `java==1.8`.

**Comment by dxli94** [comment]
Hi @moskomule,

Thanks for your feedback. You're correct. The cococap evaluation requires Java 8.

We'll update the instructions to reflect this.

Thanks.

**Comment by moskomule** [comment]
Thanks!

Though it's not directly related to the topic above, I think writing `torch==1.10.0` in the `requirements-dev.txt` may not be a good idea because it will download incompatible CUDA for Ampere GPUs.

**Comment by dxli94** [comment]
@moskomule this is a valid point. An option is to install torch 1.10 with cuda 11, e.g. `torch==1.10+cu113`.

We will be better testing before relaxing the torch version constraints.

Thanks.

**Comment by lxr-1204** [comment]
I want to say that torch1.10 may not match peft
