### ISSUE TITLE
Image captioning using COCO

### ISSUE THREAD

**Issue by look4pritam** [salesforce/LAVIS#553]
I was trying to train image captioning using COCO with following script.
run_scripts/blip2/train/train_caption_coco.sh
It requires configuration lavis/projects/blip2/train/caption_coco_ft.yaml

It is missing from the git repository.
Where can I find it?

**Comment by look4pritam** [comment]
Sorry I got the file.

**Comment by shams2023** [comment]
> caption_

Hello!
May I ask if I also want to use BLIP2 for caption operations? How can I achieve this?
I need your help, thank you!

**Comment by look4pritam** [comment]
See following links
https://huggingface.co/Salesforce/blip2-opt-2.7b
https://huggingface.co/Salesforce/blip2-opt-6.7b-coco

Here example code using huggingface transformer is shown. It works perfectly alright.
