### ISSUE TITLE
cannot import name '_expand_mask'

### ISSUE THREAD

**Issue by Nyuo70** [salesforce/LAVIS#571]
When I try to execute `train.py`, I encounter the following error:
ImportError: cannot import name '_expand_mask' from 'transformers.models.clip.modeling_clip' (/home/tmp/onishi3n/Honki/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py)

**Comment by boop-yyt** [comment]
After updating the "transformers" version to either 4.28 or 4.31, the issue was resolved.

**Comment by Nyuo70** [comment]
Thank you!

**Comment by Nyuo70** [comment]
resolved

**Comment by vedant001** [comment]
after updating it to transformers==4.31.0 it throws error of 
RuntimeError: Failed to import diffusers.pipelines.controlnet.pipeline_controlnet_blip_diffusion because of the following error (look up to see its traceback):
cannot import name 'is_scaled_image' from 'transformers.image_utils'

**Comment by Cuppinono** [comment]
me too, I have this question

**Comment by Preciousrs** [comment]
> me too, I have this question
Do you resolve this question?

**Comment by qiangtang2017** [comment]
transformers 4.31.0 is ok

**Comment by vedant001** [comment]
pip install diffusers==0.15.0
try above line
@Cuppinono @Preciousrs

**Comment by Abecid** [comment]
I am getting this error with transformers 4.35.2

**Comment by Hambaobao** [comment]
`ImportError: cannot import name '_expand_mask' from 'transformers.models.bloom.modeling_bloom' (/usr/local/lib/python3.9/dist-packages/transformers/models/bloom/modeling_bloom.py)`
I got this error with transformers 4.36.1.

**Comment by ghoshsubh** [comment]
> `ImportError: cannot import name '_expand_mask' from 'transformers.models.bloom.modeling_bloom' (/usr/local/lib/python3.9/dist-packages/transformers/models/bloom/modeling_bloom.py)` I got this error with transformers 4.36.1.

I have the same error with transformers 4.36.2

**Comment by iwannabewater** [comment]
> I solve the error with transformers 4.33.0I solved the error with transformers 4.33.0

Thx, this works for me!

**Comment by maulikmadhavi** [comment]
Copy the function definition from previous transformer libraries
```
# Copied from transformers.models.bart.modeling_bart._expand_mask
def _expand_mask(mask: torch.Tensor, dtype: torch.dtype, tgt_len: Optional[int] = None):
    """
    Expands attention_mask from `[bsz, seq_len]` to `[bsz, 1, tgt_seq_len, src_seq_len]`.
    """
    bsz, src_len = mask.size()
    tgt_len = tgt_len if tgt_len is not None else src_len

    expanded_mask = mask[:, None, None, :].expand(bsz, 1, tgt_len, src_len).to(dtype)

    inverted_mask = 1.0 - expanded_mask

    return inverted_mask.masked_fill(inverted_mask.to(torch.bool), torch.finfo(dtype).min)
   ```
   
   Then install using `python setup.py install`. 
   
   Btw I have already created pull request, refer to my cloned version `https://github.com/maulikmadhavi/LAVIS/tree/patch-requirements`. Thanks

**Comment by Deephug969** [comment]
transformers 4.31.0 is ok!
