### ISSUE TITLE
Ask for weight of blip2_vicuna

### ISSUE THREAD

**Issue by zdxff** [salesforce/LAVIS#580]
When I read the paper "Qwen-VL: A Frontier Large Vision-Language Model with Versatile Abilities", I find they use BLIP-2 (Vicuna-13B) to test in table 5, 6. But I do not find this model's download url. Could you solve my problem?

**Comment by Hannahhhhhhhhhhhh** [comment]
Hi, did you get the weight of BLIP2(Vicuna-13B)？

**Comment by spetryk** [comment]
You can download the weights from the link in the config: https://github.com/salesforce/LAVIS/blob/main/lavis/configs/models/blip2/blip2_instruct_vicuna13b.yaml#L11

**Comment by zdxff** [comment]
> You can download the weights from the link in the config: https://github.com/salesforce/LAVIS/blob/main/lavis/configs/models/blip2/blip2_instruct_vicuna13b.yaml#L11

Thank you for your answer！
