### ISSUE TITLE
Difference between blip2_pretrained.pth and blip2_pretrained_opt2.7b.pth

### ISSUE THREAD

**Issue by look4pritam** [salesforce/LAVIS#581]
Thanks for wonderful work.
I am new to BLIP2. 
I am having few queries.
What is the difference between blip2_pretrained.pth and blip2_pretrained_opt2.7b.pth ?

blip2_pretrained_opt2.7b.pth is pretrained using keeping ViT freezed and opt2.7 also freezed. I may be incorrect.

What about blip2_pretrained.pth? How is it generated ? Is opt2.7 not used?

**Comment by look4pritam** [comment]
Thanks for the wonderful work.
blip2_pretrained.pth is the output of BLIP2 pretrain stage one. OPT i.e. LLM are not used.

blip2_pretrained_opt2.7b is the output of BLIP2 pretrain stage two. OPT i.e. LLM is used.

It was so simple and I didn't get it.

**Comment by NearianChen** [comment]
> Thanks for the wonderful work. blip2_pretrained.pth is the output of BLIP2 pretrain stage one. OPT i.e. LLM are not used.
> 
> blip2_pretrained_opt2.7b is the output of BLIP2 pretrain stage two. OPT i.e. LLM is used.
> 
> It was so simple and I didn't get it.

You're great, Bro!
I don't know about this question, So I check and search for it. Then I find this issue and look your answer. 
Thanks for your issue and reply.
