### ISSUE TITLE
CODE to reproduce examples in LAVIS technical report

### ISSUE THREAD

**Issue by behroozazarkhalili** [salesforce/LAVIS#6]
Hi,
I would be grateful if you could kindly provide the code to regenerate the other test cases provided in the technical report.

I'm really interested in to regenerate zero shot classification, text localisation, multimodal classification, etc.

**Comment by dxli94** [comment]
Hi @behroozazarkhalili,

Thanks for your interest and feedback.

We believe it is a good idea to provide examples as part of documentation, so I'm labeling the issue as such.

For now, you can already find these code in our streamlit demo code. Can you try [run the demo](https://github.com/salesforce/LAVIS#resources-and-tools) and look into the [source code ](https://github.com/salesforce/LAVIS/tree/main/app)to reproduce?

Thanks.

**Comment by behroozazarkhalili** [comment]
Hi Dongxu,
Thanks for your prompt response and consideration.

I'm trying it and keep you posted.

**Comment by behroozazarkhalili** [comment]
> Hi @behroozazarkhalili,
> 
> Thanks for your interest and feedback.
> 
> We believe it is a good idea to include these examples as part of documentation, so I'm labeling the issue as such. We plan to do this in the coming week.
> 
> For now, you can already find these code in our streamlit demo code. Can you try [run the demo](https://github.com/salesforce/LAVIS#resources-and-tools) and look into the [source code ](https://github.com/salesforce/LAVIS/tree/main/app)to reproduce?
> 
> Thanks.

Hi Dongxu,
I have received the following error:
`File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
File "/home/ermia/PycharmProjects/LAVIS/app/main.py", line 8, in <module>
    from app.multipage import MultiPage`

**Comment by dxli94** [comment]
Hi @behroozazarkhalili @AzizRaies, examples are up now. Kindly check them out. 

Thanks.
