### ISSUE TITLE
Reproduce the result on okvqa

### ISSUE THREAD

**Issue by YHWmz** [salesforce/LAVIS#63]
Hi, I use the scripts LAVIS/run_scripts/blip/train/train_okvqa.sh to finetune blip on okvqa. However, the result in epoch 7 is only 45.12, which has a large gap between the result [55.4](https://opensource.salesforce.com/LAVIS//latest/benchmark.html) you proposed. Are there any hyperparameter that need to modify in LAVIS/lavis/projects/blip/train/okvqa_ft.yaml ? 

It would be highly appreciated if you could give some help.

**Comment by dxli94** [comment]
Hi @YHWmz ,

The 55.4 result is obtained by initializing from VQAv2 checkpoint. Can you confirm you are loading this checkpoint?

Thanks.

**Comment by YHWmz** [comment]
> Hi @YHWmz ,
> 
> The 55.4 result is obtained by initializing from VQAv2 checkpoint. Can you confirm you are loading this checkpoint?
> 
> If directly tuned on OKVQA from pretraiend checkpoint, ~45 is expected.
> 
> Thanks.

Thanks for your replay.

I find that the model initializing from 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_vqa_capfilt_large.pth' in LAVIS/lavis/models/base_model.py line 101.

I am not sure whether the ‘model_base_vqa_capfilt_large.pth’ is VQAv2 checkpoint？By the way, I didn't change the code in LAVIS but just run the script LAVIS/run_scripts/blip/train/train_okvqa.sh

**Comment by YHWmz** [comment]
I also try to run LAVIS/run_scripts/blip/train/train_aokvqa.sh and the model is also initializing from 'model_base_vqa_capfilt_large.pth'. Then I find the result is ~50, which also lower than 56.2 in [Benchmark](https://opensource.salesforce.com/LAVIS//latest/benchmark.html).

**Comment by dxli94** [comment]
Are you using the same configurations as in .yaml? Note that OKVQA and AOKVQA dataset sizes are quite small. If you change batch size etc, you may also need to adjust other hparams accordingly to reach the best results.

**Comment by YHWmz** [comment]
Oh, I change the bz to 12. Maybe that is the problem. 

I'll let you know when I figure it out.

Thank u so much for the help~

**Comment by YHWmz** [comment]
Solved. 

The problem is the bz. 

Thanks for your help again.

**Comment by dxli94** [comment]
Glad to hear.
