### ISSUE TITLE
Hugging Face integration of `BLIP`

### ISSUE THREAD

**Issue by younesbelkada** [salesforce/LAVIS#64]
Dear authors,

We have a working implementation of `BLIP` and 3 of its variants in huggingface `transformers` (image captioning, visual question answering, image text retrieval): https://github.com/huggingface/transformers/pull/20716 that is not merged yet

The license of the repository and model states that: 
```
3. Neither the name of [Salesforce.com](http://salesforce.com/) nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
```

We would like to promote the addition of this architecture to `transformers` library. Therefore I would like to ask you the permission for promoting this contribution

Thank you very much in advance

**Comment by dxli94** [comment]
Hi @younesbelkada, thanks a lot for this.

I don't see any issue myself. Please allow us a few days to have an internal discussion. Will get back soon.

**Comment by dxli94** [comment]
Hi @younesbelkada , thanks for the patience.

We have an internal discussion and would be happy to see BLIP supported on HF. Please go ahead with the integration with acknowledging the publication, authors and our organization.

Thanks for your interest in our work.

**Comment by younesbelkada** [comment]
Thanks so much for this great news
The integration has been announced through various medias: 
Twitter: https://twitter.com/younesbelkada/status/1605489647395540992?s=20&t=b9XNjRBW1o-Mu2NkERvrLw
LI: [https://www.linkedin.com/posts/younes-belkada-b1a903145_deeplearning-multimodal-api-a[…]721751482368-T49x?utm_source=share&utm_medium=member_desktop](https://www.linkedin.com/posts/younes-belkada-b1a903145_deeplearning-multimodal-api-activity-7011254721751482368-T49x?utm_source=share&utm_medium=member_desktop)
Thanks again for sharing this great model! Let's collaborate more whenever we can
