### ISSUE TITLE
Possible to remove hard dependency on torch 1.10.0 ?

### ISSUE THREAD

**Issue by codedecde** [salesforce/LAVIS#65]
Would it be possible to remove the hard dependency on torch == 1.10.0 (this line) to something softer like torch >= 1.10.0 ([this line](https://github.com/salesforce/LAVIS/blob/250ac10d011a021c85ebac4bec5303d443e28c16/requirements-dev.txt#L21)) ?

**Comment by dxli94** [comment]
torch==1.10.0 is required to fully reproduce our experiment results.

Updating torch to newest version does not break the training. But we did observe differences in performance. See issue (https://github.com/salesforce/LAVIS/issues/40) for reference.

Thanks.

**Comment by dxli94** [comment]
This is now relaxed to torch>=1.10 in https://github.com/salesforce/LAVIS/commit/cd4db98c93d87abe926c9c0e21093f4c56f856de.

However, please be aware the for best reproducing the training for ALBEF and BLIP models, torch=1.10 is recommended.
