### ISSUE TITLE
When using instructblip to evaluate the okvqa data set, there is nothing in the output path

### ISSUE THREAD

**Issue by Fym68** [salesforce/LAVIS#664]
![问题](https://github.com/salesforce/LAVIS/assets/92427894/ccceaa55-6320-41e6-a334-407f08c15405)
I want to use the instructblip model to evaluate okvqa and textvqa, but my output has no content, making me wonder if my operation is correct. 
Could someone provide evaluation script or implementation guideline for okVQA or textvqa?

**Comment by LEE-IU** [comment]
Have you found the evaluation script or guidelines for TextVQA? The accuracy I obtained with my own evaluation code is only around 20%. If you have solved this issue, could you please provide some assistance?
