### ISSUE TITLE
The results of DocVQA, infoVQA, and OCRVQA evaluating the instructblip model are very low

### ISSUE THREAD

**Issue by Fym68** [salesforce/LAVIS#671]
Has anyone used DocVQA, infoVQA, and OCRVQA to evaluate the instructblip model? What is your accuracy? The accuracy I get is very very low

**Comment by Z1zs** [comment]
Hi, I got the same low results on DocVQA(0.0576 anls_score), different from the reported performance in DocVQA official(0.5156). Have you found the reason for it?
