### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by behroozazarkhalili** [salesforce/LAVIS#7]
Hi Dongxu,
I have received the following error when running the above command:
`bash run_scripts/run_demo.sh`

`ModuleNotFoundError: No module named 'app'`
`File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script exec(code, module.__dict__)`

`File "/home/ermia/PycharmProjects/LAVIS/app/main.py", line 8, in <module> from app.multipage import MultiPage`

I'm digging the code to find the reasons for the error.

**Comment by dxli94** [comment]
I tested on new environments and can't reproduce.

Can you confirm you are using the environment with LAVIS properly installed?

Thanks.

**Comment by behroozazarkhalili** [comment]
> I tested on clean environments and can't reproduce.
> 
> Steps are below:
> 
> 1. install LAVIS: `cd LAVIS && pip install .`
> 2. activate demo: `bash run_script/run_demo.sh`
> 
> Otherwise, can you confirm you are using the environment with LAVIS properly installed?
> 
> Thanks.

Yeah. It works. just change `bash run_script/run_demo.sh` to `bash run_scripts/run_demo.sh`
