### ISSUE TITLE
How can I change cache_root?

### ISSUE THREAD

**Issue by minnsu03** [salesforce/LAVIS#703]
I'm trying to evaluate blip-2 on mscoco dataset. 
functions in lavis.common.utils.py are written to use cache memory. but,I can't use cache memory because my working space is on GPU server. so i want to change cache_root. working space starts with /home/work/ so I changed  env.cache_root in lavis/configs/default.yaml to /home/work/LAVIS/ . but it still doesnt work.

I could get below error
```
 work@main1[X0KjpOeq-session]:~/LAVIS$ cd lavis/datasets/download_scripts/ && python download_coco.py
WARNING:root:Pytorch pre-release version 2.2.0a0+81ea7a4 - assuming intent to test it
Downloading http://images.cocodataset.org/zips/train2014.zip to train
Downloading http://images.cocodataset.org/zips/train2014.zip to /export/home/.cache/lavis/coco/download/train2014.zip
Failed to download or extracting datasets. Aborting.
```
Is there any solution to change "/export/home/.cache/lavis/coco/download/train2014.zip" to "/home/work/LAVIS/lavis/coco/download/train2014.zip"??

Even if the path is forcibly changed, another error occurs at evaluate.py afterwards.

**Comment by CH7auAI** [comment]
hi, I have the same problem, could you tell me how you change the cache_root?

**Comment by zahraborghei** [comment]
hi, you can change it from this directory:
lavis/configs/default.yaml

**Comment by Echoandland** [comment]
Hi, how did you finally solve it? Thanks
