### ISSUE TITLE
A question for BLIP2 Q-Former

### ISSUE THREAD

**Issue by nbqu** [salesforce/LAVIS#706]
Hello, I have a question while I'm reviewing the codebase of BLIP2 myself. In [bilp2_qformer#L76](https://github.com/salesforce/LAVIS/blob/ac8fc98c93c02e2dfb727e24a361c4c309c8dbbc/lavis/models/blip2_models/blip2_qformer.py#L76), it copies the weight if the name contains `"_query"`.
I cannot understand what is this for, so I checked `BertLMHeadModel`(where the q-former originated from) parameters and what parameters are named with `_query`. But I found that there is no such parameter that contains `_query`.
```python
import transformers
from transformers import BertLMHeadModel

print(transformers.__version__)  # '4.41.1'
model = BertLMHeadModel.from_pretrained("bert-base-uncased")
for n, p in model.named_parameters():
  if "_query" in n:
    print(n, p.shape)

(prints nothing)
```

What is this used for? What supposed to be done with this code?

Please let me know if you need more information for my question.

Thanks for your answer :)

**Comment by nbqu** [comment]
Seems to be resolved myself. I found that the `BertLMHeadModel` is not from transformers, but the modified version in lavis. Closing.

**Comment by sdwulxr** [comment]
Hello, may I ask you a question? I'd like to incorporate the Q-former module from blip2 into my own project, specifically the first stage of blip2. However, the author has provided too many files and I'm finding it difficult to understand the code structure. This problem has been troubling me for a long time. Could you please help me? I would really appreciate it

**Comment by nbqu** [comment]
> Hello, may I ask you a question? I'd like to incorporate the Q-former module from blip2 into my own project, specifically the first stage of blip2. However, the author has provided too many files and I'm finding it difficult to understand the code structure. This problem has been troubling me for a long time. Could you please help me? I would really appreciate it

Providing more details would help me find out what you exactly need. Basically comparing codes and papers would be helpful.

**Comment by sdwulxr** [comment]
Thank you very much for your reply. My research direction is sentiment analysis. I got some inspiration from an article I've been reading recently. I want to use the first half of the structure diagram in this article, where the obtained query is related to the fine-grained features of the image aspect. I would like to use this query in my own paper, but the author of this article did not provide the source code. So I'm here trying to find the code related to this part, unfortunately, I can't understand the structure. Thank you again for your reply.
[2024.lrec-main.180.pdf](https://github.com/user-attachments/files/17005135/2024.lrec-main.180.pdf)
![architecture](https://github.com/user-attachments/assets/ca7218df-f4d5-409a-928e-21fe8bbb23f0)

**Comment by sdwulxr** [comment]
> > Hello, may I ask you a question? I'd like to incorporate the Q-former module from blip2 into my own project, specifically the first stage of blip2. However, the author has provided too many files and I'm finding it difficult to understand the code structure. This problem has been troubling me for a long time. Could you please help me? I would really appreciate it
> 
> Providing more details would help me find out what you exactly need. Basically comparing codes and papers would be helpful.

I'm looking forward to your reply ! Thank you very much
