### ISSUE TITLE
blip3-ocr and blip3-grounding links are not working 

### ISSUE THREAD

**Issue by cooleel** [salesforce/LAVIS#733]
Thanks for the amazing work!
Could you please fix the links of these datasets? Thanks.

**Comment by azshue** [comment]
Hi @cooleel, thank you for your interests in our work!
We plan to make the model and dataset cards available later today (we're working on final reviews.)

Will let you know when they're ready.

**Comment by azshue** [comment]
Thank y'all for you interests in our work. 

Update on this threads: all 4 models are now live on huggingface hub: https://huggingface.co/collections/Salesforce/xgen-mm-1-models-662971d6cecbf3a7f80ecc2e.
For the two datasets, they're still undergoing internal reviews. 

We'll keep you posted on the progress. Thank you for your patience.

**Comment by azshue** [comment]
Hi, sorry for the late update. Both datasets are available under the [xGen-MM collection](https://huggingface.co/collections/Salesforce/xgen-mm-1-models-and-datasets-662971d6cecbf3a7f80ecc2e) (They've been public for a couple days, sorry about the delayed update.)

Thank you again for being patient!
