### ISSUE TITLE
Request for Example: Fine-tuning BLIP-3 on an Interleaved Text-Image Dataset

### ISSUE THREAD

**Issue by LostXine** [salesforce/LAVIS#736]
Hello,

Thank you for the amazing work you’ve done on BLIP-3 release. I really appreciate the effort that has gone into it, and I understand that the team has been busy with the code release.

Would it be possible to provide an example of how to fine-tune BLIP-3 on an interleaved text-image dataset? 
The current readme only shows an example with one image per conversation and I also had a hard time finding `scripts/example_finetune_xgenmmv1-phi3_mini_4k_instruct.sh` mentioned in readme. Please forgive me if I missed any of them.

Thanks again for your hard work and for considering this request!

Best regards,

Xiang Li

**Comment by azshue** [comment]
Hi @LostXine, thank you for trying out our code and feedback. 

There were some files that were ignored in my initial commit. Thank you for bringing this up. We have uploaded the missing script and an example data config file (`data_configs/example_data_config.yaml`).

The launch script for multi-image fine-tuning is the same as the single-image one provided in the repo. In terms of data format, it should follow same as the example format provided in README.md. So, for example, if you want to use [Mantis-Instruct](https://huggingface.co/datasets/TIGER-Lab/Mantis-Instruct), you should convert some keys in their data entry, (i.e.,  `"role": "user"` -> `"from": "human"`; `"content"` -> `"value"`)

Thank you for being patient. Feel free to let me know if you have any other questions.

**Comment by LostXine** [comment]
Hi @azshue ,

Thank you so much for your quick reply and detailed instructions. With the newly updated files, I can now understand how it works much better.

Just a note for people who are going to train this model on an interleaved dataset, please correct me if I'm wrong. 
Based on [this code](https://github.com/salesforce/LAVIS/blob/69e951d5dd87139757d7dc6fd1a2d9f260c690d3/open_flamingo/train/sft_data_utils.py#L419-L432), if you have multiple images in one conversation, you can turn [this image item in the dataset](https://github.com/salesforce/LAVIS/blob/69e951d5dd87139757d7dc6fd1a2d9f260c690d3/README.md?plain=1#L124) into a list of images (i.e., `"image": ["coco/train2017/000000033471.jpg", "coco/train2017/000000033472.jpg", ...], `), and the current code is designed to handle it seamlessly. 

Thanks again for your great effort in this project.

Best regards,

Xiang Li
