### ISSUE TITLE
How to download pretrained_ckpt="/path/to/the/base/model.pt" ?

### ISSUE THREAD

**Issue by HuichiZhou** [salesforce/LAVIS#737]

**Comment by azshue** [comment]
Hi @HuichiZhou, thank you for trying out our code. 

We just uploaded a script that converts our base model from Huggingface hub to a local pytorch checkpoint. Please check out [this section](https://github.com/salesforce/LAVIS/tree/xgen-mm?tab=readme-ov-file#base-model-weight-preparation) in README for more details.

Thank you for your feedback!

**Comment by HuichiZhou** [comment]
> Hi @HuichiZhou, thank you for trying out our code.
> 
> We just uploaded a script that converts our base model from Huggingface hub to a local pytorch checkpoint. Please check out [this commit](https://github.com/salesforce/LAVIS/commit/69e951d5dd87139757d7dc6fd1a2d9f260c690d3) and [this section](https://github.com/salesforce/LAVIS/tree/xgen-mm?tab=readme-ov-file#base-model-weight-preparation) in README for more details.
> 
> Thank you for your feedback!

Thanks!
