### ISSUE TITLE
How to use multiple GPUs when using the BLIP model trained on the VQAv2 dataset. (or any other models in LAVIS)

### ISSUE THREAD

**Issue by behroozazarkhalili** [salesforce/LAVIS#74]
Hi everyone,
Could you please let me know how I can set the number of GPUs or their IDs when using the BLIP VQA model trained on the VQAv2 dataset?

Generally, I have no idea how to use more than one GPU in LAVIS. I would be grateful if you could let me know how to do so.

**Comment by dxli94** [comment]
Hi @behroozazarkhalili, thanks for your interest.

This sounds to me not a LAVIS-specific question. For distributed training, I'd recommend take a look at the minimal example at the pytorch official tutorial: https://pytorch.org/tutorials/intermediate/ddp_tutorial.html.

Thanks.
