### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by junqiangchen** [salesforce/LAVIS#742]
Hi, i have installed lavis with pip install salesforce-lavis.
`C:\Users\Administrator\Downloads\LAVIS-main>pip install salesforce-lavis
WARNING: Ignoring invalid distribution -rotobuf (c:\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\anaconda3\lib\site-packages)
Collecting salesforce-lavis
  Downloading salesforce_lavis-1.0.2-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: contexttimer in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.3.3)
Requirement already satisfied: decord in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.6.0)
Requirement already satisfied: einops>=0.4.1 in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.6.0)
Requirement already satisfied: fairscale==0.4.4 in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.4.4)
Requirement already satisfied: ftfy in c:\anaconda3\lib\site-packages (from salesforce-lavis) (6.1.3)
Requirement already satisfied: iopath in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.1.10)
Requirement already satisfied: ipython in c:\anaconda3\lib\site-packages (from salesforce-lavis) (7.16.1)
Requirement already satisfied: omegaconf in c:\anaconda3\lib\site-packages (from salesforce-lavis) (2.3.0)
Requirement already satisfied: opencv-python-headless==4.5.5.64 in c:\anaconda3\lib\site-packages (from salesforce-lavis) (4.5.5.64)
Requirement already satisfied: opendatasets in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.1.22)
Requirement already satisfied: packaging in c:\anaconda3\lib\site-packages (from salesforce-lavis) (23.0)
Requirement already satisfied: pandas in c:\anaconda3\lib\site-packages (from salesforce-lavis) (1.3.5)
Requirement already satisfied: plotly in c:\anaconda3\lib\site-packages (from salesforce-lavis) (5.24.0)
Requirement already satisfied: pre-commit in c:\anaconda3\lib\site-packages (from salesforce-lavis) (3.5.0)
Requirement already satisfied: pycocoevalcap in c:\anaconda3\lib\site-packages (from salesforce-lavis) (1.2)
Requirement already satisfied: pycocotools in c:\anaconda3\lib\site-packages (from salesforce-lavis) (2.0.7)
Requirement already satisfied: python-magic in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.4.27)
Requirement already satisfied: scikit-image in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.19.3)
Requirement already satisfied: sentencepiece in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.2.0)
Requirement already satisfied: spacy in c:\anaconda3\lib\site-packages (from salesforce-lavis) (3.7.6)
Requirement already satisfied: streamlit in c:\anaconda3\lib\site-packages (from salesforce-lavis) (1.38.0)
Requirement already satisfied: timm==0.4.12 in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.4.12)
Requirement already satisfied: torch>=1.10.0 in c:\anaconda3\lib\site-packages (from salesforce-lavis) (1.12.1+cu113)
Requirement already satisfied: torchvision in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.13.1+cu113)
Requirement already satisfied: tqdm in c:\anaconda3\lib\site-packages (from salesforce-lavis) (4.66.1)
Requirement already satisfied: transformers<4.27,>=4.25.0 in c:\anaconda3\lib\site-packages (from salesforce-lavis) (4.26.1)
Requirement already satisfied: webdataset in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.2.100)
Requirement already satisfied: wheel in c:\anaconda3\lib\site-packages (from salesforce-lavis) (0.34.2)
Requirement already satisfied: numpy>=1.14.5 in c:\anaconda3\lib\site-packages (from opencv-python-headless==4.5.5.64->salesforce-lavis) (1.22.3)
Requirement already satisfied: typing-extensions in c:\anaconda3\lib\site-packages (from torch>=1.10.0->salesforce-lavis) (4.10.0)
Requirement already satisfied: filelock in c:\anaconda3\lib\site-packages (from transformers<4.27,>=4.25.0->salesforce-lavis) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in c:\anaconda3\lib\site-packages (from transformers<4.27,>=4.25.0->salesforce-lavis) (0.12.1)
Requirement already satisfied: pyyaml>=5.1 in c:\anaconda3\lib\site-packages (from transformers<4.27,>=4.25.0->salesforce-lavis) (6.0)
Requirement already satisfied: regex!=2019.12.17 in c:\anaconda3\lib\site-packages (from transformers<4.27,>=4.25.0->salesforce-lavis) (2020.6.8)
Requirement already satisfied: requests in c:\anaconda3\lib\site-packages (from transformers<4.27,>=4.25.0->salesforce-lavis) (2.29.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\anaconda3\lib\site-packages (from transformers<4.27,>=4.25.0->salesforce-lavis) (0.13.3)
Requirement already satisfied: colorama in c:\anaconda3\lib\site-packages (from tqdm->salesforce-lavis) (0.4.6)
Requirement already satisfied: wcwidth<0.3.0,>=0.2.12 in c:\anaconda3\lib\site-packages (from ftfy->salesforce-lavis) (0.2.13)
Requirement already satisfied: portalocker in c:\anaconda3\lib\site-packages (from iopath->salesforce-lavis) (2.10.1)
Requirement already satisfied: setuptools>=18.5 in c:\anaconda3\lib\site-packages (from ipython->salesforce-lavis) (49.2.0.post20200714)
Requirement already satisfied: jedi>=0.10 in c:\anaconda3\lib\site-packages (from ipython->salesforce-lavis) (0.17.1)
Requirement already satisfied: decorator in c:\anaconda3\lib\site-packages (from ipython->salesforce-lavis) (4.4.2)
Requirement already satisfied: pickleshare in c:\anaconda3\lib\site-packages (from ipython->salesforce-lavis) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in c:\anaconda3\lib\site-packages (from ipython->salesforce-lavis) (4.3.3)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\anaconda3\lib\site-packages (from ipython->salesforce-lavis) (3.0.5)
Requirement already satisfied: pygments in c:\anaconda3\lib\site-packages (from ipython->salesforce-lavis) (2.17.2)
Requirement already satisfied: backcall in c:\anaconda3\lib\site-packages (from ipython->salesforce-lavis) (0.2.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\anaconda3\lib\site-packages (from omegaconf->salesforce-lavis) (4.9.3)
Requirement already satisfied: kaggle in c:\anaconda3\lib\site-packages (from opendatasets->salesforce-lavis) (1.6.17)
Requirement already satisfied: click in c:\anaconda3\lib\site-packages (from opendatasets->salesforce-lavis) (8.1.7)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\administrator\appdata\roaming\python\python38\site-packages (from pandas->salesforce-lavis) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\anaconda3\lib\site-packages (from pandas->salesforce-lavis) (2020.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\anaconda3\lib\site-packages (from plotly->salesforce-lavis) (8.5.0)
Requirement already satisfied: cfgv>=2.0.0 in c:\anaconda3\lib\site-packages (from pre-commit->salesforce-lavis) (3.4.0)
Requirement already satisfied: identify>=1.0.0 in c:\anaconda3\lib\site-packages (from pre-commit->salesforce-lavis) (2.6.0)
Requirement already satisfied: nodeenv>=0.11.1 in c:\anaconda3\lib\site-packages (from pre-commit->salesforce-lavis) (1.9.1)
Requirement already satisfied: virtualenv>=20.10.0 in c:\anaconda3\lib\site-packages (from pre-commit->salesforce-lavis) (20.25.1)
Requirement already satisfied: matplotlib>=2.1.0 in c:\anaconda3\lib\site-packages (from pycocotools->salesforce-lavis) (3.7.5)
Requirement already satisfied: scipy>=1.4.1 in c:\anaconda3\lib\site-packages (from scikit-image->salesforce-lavis) (1.10.1)
Requirement already satisfied: networkx>=2.2 in c:\anaconda3\lib\site-packages (from scikit-image->salesforce-lavis) (2.4)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in c:\anaconda3\lib\site-packages (from scikit-image->salesforce-lavis) (9.5.0)
Requirement already satisfied: imageio>=2.4.1 in c:\anaconda3\lib\site-packages (from scikit-image->salesforce-lavis) (2.33.1)
Requirement already satisfied: tifffile>=2019.7.26 in c:\anaconda3\lib\site-packages (from scikit-image->salesforce-lavis) (2023.2.28)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\anaconda3\lib\site-packages (from scikit-image->salesforce-lavis) (1.4.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (0.12.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (2.6.3)
Requirement already satisfied: jinja2 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (3.1.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\anaconda3\lib\site-packages (from spacy->salesforce-lavis) (3.4.0)
Requirement already satisfied: altair<6,>=4.0 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (5.4.1)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (1.8.2)
Requirement already satisfied: cachetools<6,>=4.0 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (5.2.0)
Requirement already satisfied: protobuf<6,>=3.20 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (3.20.3)
Requirement already satisfied: pyarrow>=7.0 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (17.0.0)
Requirement already satisfied: rich<14,>=10.14.0 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (13.7.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (0.10.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (3.1.27)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (6.0.4)
Requirement already satisfied: watchdog<5,>=2.1.5 in c:\anaconda3\lib\site-packages (from streamlit->salesforce-lavis) (4.0.2)
Requirement already satisfied: braceexpand in c:\anaconda3\lib\site-packages (from webdataset->salesforce-lavis) (0.1.7)
Requirement already satisfied: jsonschema>=3.0 in c:\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit->salesforce-lavis) (3.2.0)
Requirement already satisfied: narwhals>=1.5.2 in c:\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit->salesforce-lavis) (1.6.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit->salesforce-lavis) (4.0.9)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\anaconda3\lib\site-packages (from jedi>=0.10->ipython->salesforce-lavis) (0.7.0)
Requirement already satisfied: language-data>=1.2 in c:\anaconda3\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy->salesforce-lavis) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\anaconda3\lib\site-packages (from matplotlib>=2.1.0->pycocotools->salesforce-lavis) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\anaconda3\lib\site-packages (from matplotlib>=2.1.0->pycocotools->salesforce-lavis) (0.10.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\anaconda3\lib\site-packages (from matplotlib>=2.1.0->pycocotools->salesforce-lavis) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\anaconda3\lib\site-packages (from matplotlib>=2.1.0->pycocotools->salesforce-lavis) (1.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\anaconda3\lib\site-packages (from matplotlib>=2.1.0->pycocotools->salesforce-lavis) (2.4.7)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\anaconda3\lib\site-packages (from matplotlib>=2.1.0->pycocotools->salesforce-lavis) (6.1.1)
Requirement already satisfied: annotated-types>=0.4.0 in c:\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->salesforce-lavis) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in c:\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->salesforce-lavis) (2.16.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\anaconda3\lib\site-packages (from jinja2->spacy->salesforce-lavis) (2.1.1)
Requirement already satisfied: six>=1.5 in c:\users\administrator\appdata\roaming\python\python38\site-packages (from python-dateutil>=2.7.3->pandas->salesforce-lavis) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\anaconda3\lib\site-packages (from requests->transformers<4.27,>=4.25.0->salesforce-lavis) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda3\lib\site-packages (from requests->transformers<4.27,>=4.25.0->salesforce-lavis) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests->transformers<4.27,>=4.25.0->salesforce-lavis) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests->transformers<4.27,>=4.25.0->salesforce-lavis) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit->salesforce-lavis) (3.0.0)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy->salesforce-lavis) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy->salesforce-lavis) (0.1.5)
Requirement already satisfied: ipython-genutils in c:\anaconda3\lib\site-packages (from traitlets>=4.2->ipython->salesforce-lavis) (0.2.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy->salesforce-lavis) (1.5.4)
Requirement already satisfied: distlib<1,>=0.3.7 in c:\anaconda3\lib\site-packages (from virtualenv>=20.10.0->pre-commit->salesforce-lavis) (0.3.8)
Requirement already satisfied: platformdirs<5,>=3.9.1 in c:\anaconda3\lib\site-packages (from virtualenv>=20.10.0->pre-commit->salesforce-lavis) (4.2.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy->salesforce-lavis) (0.19.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy->salesforce-lavis) (7.0.4)
Requirement already satisfied: python-slugify in c:\anaconda3\lib\site-packages (from kaggle->opendatasets->salesforce-lavis) (8.0.3)
Requirement already satisfied: bleach in c:\anaconda3\lib\site-packages (from kaggle->opendatasets->salesforce-lavis) (3.1.5)
Requirement already satisfied: pywin32>=226 in c:\anaconda3\lib\site-packages (from portalocker->iopath->salesforce-lavis) (227)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit->salesforce-lavis) (5.0.0)
Requirement already satisfied: zipp>=3.1.0 in c:\anaconda3\lib\site-packages (from importlib-resources>=3.2.0->matplotlib>=2.1.0->pycocotools->salesforce-lavis) (3.1.0)
Requirement already satisfied: attrs>=17.4.0 in c:\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->salesforce-lavis) (22.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->salesforce-lavis) (0.16.0)
Requirement already satisfied: marisa-trie>=0.7.7 in c:\anaconda3\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy->salesforce-lavis) (1.2.0)
Requirement already satisfied: mdurl~=0.1 in c:\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit->salesforce-lavis) (0.1.2)
Requirement already satisfied: wrapt in c:\anaconda3\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy->salesforce-lavis) (1.16.0)
Requirement already satisfied: webencodings in c:\anaconda3\lib\site-packages (from bleach->kaggle->opendatasets->salesforce-lavis) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\anaconda3\lib\site-packages (from python-slugify->kaggle->opendatasets->salesforce-lavis) (1.3)
Downloading salesforce_lavis-1.0.2-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 1.8/1.8 MB 92.7 kB/s eta 0:00:00
WARNING: Ignoring invalid distribution -rotobuf (c:\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\anaconda3\lib\site-packages)
DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: salesforce-lavis
Successfully installed salesforce-lavis-1.0.2`

my python is 3.8.3.
run `from lavis.models import model_zoo`,
the error like this:
 RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf .
and i check my numpy verison is 1.22.3.so i uninstall it,and install numpy 1.24.4,
the error like this:
AttributeError: module 'numpy' has no attribute 'typeDict'.
which version should i install numpy?
thank you!!

**Comment by junqiangchen** [comment]
i use conda create new python environment,it works.

**Comment by helloyuning** [comment]
> 我使用 conda 创建新的 python 环境，它起作用了。

Hello, I met the same issue
How can you solve the problem

thanks
