### ISSUE TITLE
Inquiry about sharing `open_flamingo.train.data` used in BLIP-3

### ISSUE THREAD

**Issue by weiyao-Wang** [salesforce/LAVIS#751]
Thank you for open-sourcing such a cool project of BLIP-3. I found that there are some codes that are not provided in the `xgen-mm` branch, specifically, `open_flamingo/train/data` and `open_flamingo/train/data_utils`. I am aware that those codes are different than the original open_flamingo, so would it be possible to release them as it would help understand how the BLIP-3 handle the datasets?

Thank you.

**Comment by azshue** [comment]
Hi @weiyao-Wang,

Thank you for your interest in our code. 

Yes, we substantially rewrote the dataloaders in this branch for supervised fine-tuning compared to the original open-flamingo implementation. You can find our new data loaders and related functions in [`open_flamingo/train/sft_data_utils.py`](https://github.com/salesforce/LAVIS/blob/xgen-mm/open_flamingo/train/sft_data_utils.py). 

Let me know if you have other questions. Thanks!

**Comment by weiyao-Wang** [comment]
Hi @azshue 

Thanks for guiding me with the code! I would actually like to ask about how you handle mixtures of datasets (i.e., text-image pairs and text-image interleaved). Could you guide me with this? Thanks!

**Comment by SeinCore** [comment]
> Hi @azshue
> 
> Thanks for guiding me with the code! I would actually like to ask about how you handle mixtures of datasets (i.e., text-image pairs and text-image interleaved) as well as some logistics of inputting them (e.g., `SUPPORTED_DATASETS` and `get_data`). Could you provide me with this file? Thanks!

Hi,have u get it?

**Comment by azshue** [comment]
Hi all,

Apologies for the late reply. Thank you for your interests in adopting our code.

During fine-tuning, our code does not distinguish image-text pairs from interleaved image-text data. The mixture of datasets are concatenated together into [one dataset](https://github.com/salesforce/LAVIS/blob/xgen-mm/open_flamingo/train/sft_data_utils.py#L299). The mixture of datasets are specified in a data_config file (see [example](https://github.com/salesforce/LAVIS/blob/xgen-mm/data_configs/example_data_config.yaml)). In the data config file, you can include both image-text pair data and interleaved data.

**Comment by weiyao-Wang** [comment]
Hi @azshue

Thanks for the response. I was asking for the pre-training logistics instead of the finetuning codes, which is clearly explained. Since I have sorted it out, I am going to close this issue. Thank you so much for your kind response.

**Comment by SeinCore** [comment]
> Hi @azshue
> 
> Thanks for the response. I was asking for the pre-training logistics instead of the finetuning codes, which is clearly explained. Since I have sorted it out, I am going to close this issue. Thank you so much for your kind response.

Could you please share how you resolved the issues during training? Specifically, may I ask what the code for SUPPORTED_DATASETS and get_data looks like? @weiyao-Wang
