### ISSUE TITLE
Wrong variable names in img2prompt_vqa Colab notebook

### ISSUE THREAD

**Issue by timdingman-scale** [salesforce/LAVIS#79]
https://colab.research.google.com/github/salesforce/LAVIS/blob/main/projects/img2prompt-vqa/img2prompt_vqa.ipynb

In the cell `Load LLM to use`, only the uncommented option uses the variable `llm_model`, which is correct. The commented options just say `model`.

**Comment by dxli94** [comment]
Hi @timdingman-scale , thanks for the well-spotting.

Are you interested in creating a PR so we can merge? Otherwise we can of course fix them ourselves.

Thanks.
