### ISSUE TITLE
Pip installable package and dependency upgrade

### ISSUE THREAD

**Issue by behroozazarkhalili** [salesforce/LAVIS#88]
Hi everyone,
First of all, thank you for such a great package,

It would be great if you could provide the users with a pip-installable version of the code on PyPI. Additionally, I believe the torch and transformer versions can be upgraded along with the Python version.

**Comment by dxli94** [comment]
Hi @behroozazarkhalili,

We are actively working on it and aim to release in the coming weeks.

If you'd like to access preview version, please try `pip install salesforce-lavis`.

Thanks.
