### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by behroozazarkhalili** [salesforce/LAVIS#9]
Hi everyone, @dxli94 
When I am running the below code, I receive the corresponding error:
```
import torch
from lavis.models import load_model_and_preprocess
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# loads BLIP caption base model, with finetuned checkpoints on MSCOCO captioning dataset.
# this also loads the associated image processors
model, vis_processors, _ = load_model_and_preprocess(name="blip_caption", model_type="base_coco", is_eval=True, device=device)
```
The error is about loading the model from a path, which seems unreachable due to some unknown issue.
```
 raise HTTPError(req.full_url, code, msg, hdrs, fp)
          │         │   │         │     │    │     └ <http.client.HTTPResponse object at 0x7fa4f4114820>
          │         │   │         │     │    └ <http.client.HTTPMessage object at 0x7fa4f41149a0>
          │         │   │         │     └ 'Forbidden'
          │         │   │         └ 403
          │         │   └ <property object at 0x7fa58770f1d0>
          │         └ <urllib.request.Request object at 0x7fa4f413d790>
          └ <class 'urllib.error.HTTPError'>
```
Which is related to the following file.
`https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP/blip_coco_caption_base.pth
`

Could you please kindly make the models available somewhere else that can easily be accessible?

**Comment by dxli94** [comment]
Hi @behroozazarkhalili, thanks for your interest.

Our model weights are hosted on Google Cloud Storage, made available for public access.

I've checked two things:
   - the[  weight ](https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP/blip_coco_caption_base.pth) is actually publicly available. Can you try access it manually?
   - I set up a clean environment and run the code snippet above, can't seem to reproduce the 403 error and am able to download and run inference without problem. Could you try maybe in a few moments?

Let us know. Thanks.

**Comment by behroozazarkhalili** [comment]
Hi @dxli94 
1. It is not available for me, and I received the same error.
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>We're sorry, but this service is not available in your location</Details>
</Error>
```
I have already tried it many times.
2. As I explained, Google Cloud Storage cannot be accessible to everyone indeed.

Is it possible to put the files somewhere else in the cloud?

**Comment by dxli94** [comment]
Hi @behroozazarkhalili,

It is possible to make files hosted on Google Cloud Storage publicly available. We've been doing this without issues in the past.

I've just tried on a machine connected to public network and can download the weight.

I can't see how this happens as for now. Is it possible due to firewall setups in your local network?

Thanks.

**Comment by behroozazarkhalili** [comment]
> Hi @behroozazarkhalili,
> 
> It is possible to make files hosted on Google Cloud Storage publicly available. We've been doing this without issues in the past and we follow the same practice for LAVIS.
> 
> I've just tried on a machine connected to public network and can download the weight.
> 
> I can't see how this happens as for now. Is it possible due to firewall setups in your local network?
> 
> Also, is it just for this checkpoint or for all others as well?
> 
> Thanks.

I tried with three different networks and received the same error.
I have the issue for all the models I have tried so far.

BTW, it would be great if you could provide alternative addresses alongside the primary address.

Thanks.

**Comment by dxli94** [comment]
I'll look into this issue and get back.

**Comment by dxli94** [comment]
Hi, @behroozazarkhalili,

Can you help to confirm you can access this [checkpoint]([Download](https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_14M.pth)), which is used in our BLIP repository and downloaded by the public users many times without issues.

Thanks.

**Comment by behroozazarkhalili** [comment]
> Hi, @behroozazarkhalili,
> 
> Can you help to confirm you can access this [checkpoint](https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_14M.pth), which was used in our BLIP repository and downloaded by the public users many times without issues.
> 
> Thanks.

Hi @dxli94 
Unfortunately, I couldn't access to the checkpoint.
