### ISSUE TITLE
How to use fp16 and int8 in the models.

### ISSUE THREAD

**Issue by behroozazarkhalili** [salesforce/LAVIS#92]
Hi there,
Could you please kindly explain how we can use the fp16 or int8 computation strategy to speed up running time? Is there any possibility of providing the models supporting fp16 or int8 if there are not any now?

**Comment by LiJunnan1992** [comment]
Hi,
For BLIP-2 models, our current implementation cast the model to fp16 or bfloat16 by default when running on GPU.

https://github.com/salesforce/LAVIS/blob/7033909c4fc66b8d0d1580bc032706c7fb5431e8/lavis/models/eva_vit.py#L441
https://github.com/salesforce/LAVIS/blob/7033909c4fc66b8d0d1580bc032706c7fb5431e8/lavis/models/blip2_models/blip2_opt.py#L76
https://github.com/salesforce/LAVIS/blob/7033909c4fc66b8d0d1580bc032706c7fb5431e8/lavis/models/blip2_models/blip2_t5.py#L81

**Comment by behroozazarkhalili** [comment]
Hi,
Thank you, but I mean all models in the model zoo.

**Comment by dxli94** [comment]
Hi,

We don't have plan to back support previous models at this stage as they are mostly small-sized. While having reduced precision help in particular hardware case, we may not be able to priortize this for now.

Thanks.
