### ISSUE TITLE
BLIP2 feature extracter/retrieval 

### ISSUE THREAD

**Issue by jn2clark** [salesforce/LAVIS#98]
Hi!
A couple of questions:
(1) What is the best way to use blip2 as a feature extractor for image-text retrieval? I did not see the same interface for blip2 here as the original blip. 
(2) Are there any metrics for single stage retrieval (text-image) for blip2 without using fusion encoder reranking?

Thanks!

**Comment by LiJunnan1992** [comment]
Hi @jn2clark, thanks for your questions.
1. We will be implementing a feature extract interface for blip2.
2. We haven't evaluated the single-stage retrieval based on contrastive similarity alone, you are more than welcomed to give it a go. Just modify this function: https://github.com/salesforce/LAVIS/blob/5ddd9b4e5149dbc514e81110e03d28458a754c5d/lavis/models/blip2_models/blip2.py#L98
